// designer/widgets/widgetPropertiesSource.js
// Writes a whole widget property list back out as the source of
// src/widgetProperties.js. The Widgets area's Export uses it, so the lists
// you curate there can be committed and become what everyone gets.
//
// The output is deterministic: widgets in catalog order (DX_WIDGET_DATA),
// a section comment per category, one property per line, keys in a fixed
// order. src/widgetProperties.js was itself produced by this function, so
// an export only differs from the committed file where you changed
// something.

import { DX_WIDGET_DATA } from '../../widgetData';

// Key order within one property definition.
const DEF_KEY_ORDER = ['name', 'label', 'type', 'options', 'default', 'bindable', 'group'];

const FILE_HEADER = `// widgetProperties.js
// The widget properties the Screens designer exposes, per widget: what the
// details panel shows, what can be bound (⚡), and what a newly dropped
// widget starts with. Read through designer/widgets/widgetPropertyDefs.js
// (getWidgetPropertyDefs), never directly — that's where the Widgets
// area's saved edits are layered on top.
//
// GENERATED by the Widgets area's Export (designer/widgets/
// widgetPropertiesSource.js). Hand edits are fine, but the next export
// rewrites the layout.
//
// A property: { name, label, type, options?, default, bindable?, group? }
//   name      the DevExtreme option; dot paths ('title.text') are expanded
//             into nested objects when the widget renders
//   type      bool | number | string | enum | color | data
//             ('data' is a collection — bind-only, no static editor)
//   options   the choices, for enum
//   bindable  false for options that name a column rather than hold a
//             value (argumentField, keyExpr…), so they can't be bound
//   group     optional heading in the details panel
`;

// A JS literal in the house style: single quotes, compact arrays.
export function toJsLiteral(value) {
  if (value === undefined) return 'undefined';
  if (value === null) return 'null';
  if (typeof value === 'string') {
    return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;
  }
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) return `[${value.map(toJsLiteral).join(',')}]`;
  const entries = Object.entries(value);
  if (entries.length === 0) return '{}';
  return `{ ${entries.map(([k, v]) => `${/^[A-Za-z_$][\w$]*$/.test(k) ? k : toJsLiteral(k)}: ${toJsLiteral(v)}`).join(', ')} }`;
}

export function defToSource(def) {
  const keys = [
    ...DEF_KEY_ORDER.filter(k => k in def && def[k] !== undefined),
    ...Object.keys(def).filter(k => !DEF_KEY_ORDER.includes(k) && def[k] !== undefined),
  ];
  return `{ ${keys.map(k => `${k}: ${toJsLiteral(def[k])}`).join(', ')} }`;
}

// widgetProperties: { [widgetName]: def[] } — every widget with a list.
export function widgetPropertiesToSource(widgetProperties) {
  const categories = DX_WIDGET_DATA.filter(w => w.assetLevel === 'category');
  const widgets = DX_WIDGET_DATA.filter(w => w.assetLevel === 'widget');
  const placed = new Set();
  const sections = [];

  const widgetBlock = (name) => {
    placed.add(name);
    const defs = widgetProperties[name];
    if (defs.length === 0) return `${name}: [],\n`;
    return `${name}: [\n${defs.map(d => `  ${defToSource(d)},`).join('\n')}\n],\n`;
  };

  categories.forEach(cat => {
    const names = widgets.filter(w => w.parentId === cat.id && widgetProperties[w.name]).map(w => w.name);
    if (names.length) sections.push({ title: cat.name, names });
  });
  const leftovers = Object.keys(widgetProperties).filter(n => !widgets.some(w => w.name === n));
  if (leftovers.length) sections.push({ title: 'Other', names: leftovers });

  const body = sections.map(({ title, names }) => {
    const rule = `// ─── ${title.toUpperCase()} `.padEnd(78, '─');
    return `${rule}\n${names.map(widgetBlock).join('\n')}`;
  }).join('\n');

  // Anything not reached above (a name that's in the catalog but under no
  // category) still has to come out.
  const missed = Object.keys(widgetProperties).filter(n => !placed.has(n));
  const tail = missed.length ? `\n${missed.map(widgetBlock).join('\n')}` : '';

  return `${FILE_HEADER}\nconst WIDGET_PROPERTIES = {\n\n${body}${tail}\n};\n\nexport { WIDGET_PROPERTIES };\n`;
}
