// DevExtreme widget configuration schemas
// Full nested configuration objects per widget.
// Copy to src/widgetConfigs.js

const WIDGET_CONFIGS = {

  // ─── GRIDS & LISTS ────────────────────────────────────────────────────────

  DataGrid: {
    allowColumnReordering: false,
    allowColumnResizing: false,
    autoNavigateToFocusedRow: false,
    cacheEnabled: true,
    cellHintEnabled: true,
    columnAutoWidth: false,
    columnChooser: { allowSearch: false, emptyPanelText: 'Drag a column to the columns area', enabled: false, height: 350, mode: 'dragAndDrop', searchTimeout: 500, title: 'Column Chooser', width: 250 },
    columnFixing: { enabled: false, texts: { fix: 'Fix', leftPosition: 'To the Left', rightPosition: 'To the Right', unfix: 'Unfix' } },
    columnHidingEnabled: false,
    columnMinWidth: undefined,
    columnResizingMode: 'nextColumn',
    columnWidth: undefined,
    columns: [],
    customizeColumns: null,
    dataSource: null,
    dateSerializationFormat: null,
    editing: { allowAdding: false, allowDeleting: false, allowUpdating: false, changes: [], confirmDelete: true, editColumnName: null, editRowKey: null, form: {}, mode: 'row', newRowPosition: 'viewportTop', popup: {}, refreshMode: 'full', selectTextOnEditStart: false, startEditAction: 'click', texts: { addRow: 'Add a row', cancelAllChanges: 'Discard changes', cancelRowChanges: 'Cancel', confirmDeleteMessage: 'Are you sure you want to delete this record?', confirmDeleteTitle: '', deleteRow: 'Delete', editRow: 'Edit', saveAllChanges: 'Save changes', saveRowChanges: 'Save', undeleteRow: 'Undelete', validationCancelChanges: 'Cancel changes' }, useIcons: false },
    elementAttr: {},
    errorRowEnabled: true,
    export: { allowExportSelectedData: false, enabled: false, formats: ['xlsx'], texts: { exportAll: 'Export all data', exportSelectedRows: 'Export selected rows', exportTo: 'Export' } },
    filterBuilder: {},
    filterBuilderPopup: {},
    filterPanel: { customizeText: null, filterEnabled: true, texts: { clearFilter: 'Clear', createFilter: 'Create Filter' }, visible: false },
    filterRow: { applyFilter: 'auto', applyFilterText: 'Apply filter', betweenEndText: 'End', betweenStartText: 'Start', operationDescriptions: {}, resetOperationText: 'Reset', showAllText: '(All)', showOperationChooser: true, visible: false },
    filterSyncEnabled: 'auto',
    filterValue: null,
    focusedColumnIndex: -1,
    focusedRowEnabled: false,
    focusedRowIndex: -1,
    focusedRowKey: null,
    grouping: { allowCollapsing: true, autoExpandAll: false, contextMenuEnabled: false, expandMode: 'buttonClick', texts: { groupByThisColumn: 'Group by This Column', groupContinuedMessage: 'Continued from the previous page', groupContinuesMessage: 'Continues on the next page', ungroup: 'Ungroup', ungroupAll: 'Ungroup All' } },
    groupPanel: { allowColumnDragging: true, emptyPanelText: 'Drag a column header here to group by that column', visible: false },
    headerFilter: { allowSearch: false, allowSelectAll: true, height: 315, search: { editorOptions: {}, enabled: false, mode: 'contains', timeout: 500 }, searchTimeout: 500, texts: { cancel: 'Cancel', emptyValue: '(Blanks)', ok: 'OK' }, visible: false, width: 252 },
    height: undefined,
    highlightChanges: false,
    hint: undefined,
    hoverStateEnabled: false,
    keyboardNavigation: { editOnKeyPress: false, enabled: true, enterKeyAction: 'startEdit', enterKeyDirection: 'none' },
    keyExpr: null,
    loadPanel: { enabled: 'auto', height: 90, indicatorSrc: '', shading: false, shadingColor: '', showIndicator: true, showPane: true, text: 'Loading...', width: 200 },
    masterDetail: { autoExpandAll: false, enabled: false, template: null },
    noDataText: 'No data',
    onAdaptiveDetailRowPreparing: null,
    onCellClick: null,
    onCellDblClick: null,
    onCellHoverChanged: null,
    onCellPrepared: null,
    onContentReady: null,
    onContextMenuPreparing: null,
    onDataErrorOccurred: null,
    onDisposing: null,
    onEditCanceled: null,
    onEditCanceling: null,
    onEditingStart: null,
    onEditorPrepared: null,
    onEditorPreparing: null,
    onExported: null,
    onExporting: null,
    onFileSaving: null,
    onFocusedCellChanged: null,
    onFocusedCellChanging: null,
    onFocusedRowChanged: null,
    onFocusedRowChanging: null,
    onInitialized: null,
    onInitNewRow: null,
    onKeyDown: null,
    onOptionChanged: null,
    onRowClick: null,
    onRowCollapsed: null,
    onRowCollapsing: null,
    onRowDblClick: null,
    onRowExpanded: null,
    onRowExpanding: null,
    onRowInserted: null,
    onRowInserting: null,
    onRowPrepared: null,
    onRowRemoved: null,
    onRowRemoving: null,
    onRowUpdated: null,
    onRowUpdating: null,
    onRowValidating: null,
    onSaved: null,
    onSaving: null,
    onSelectionChanged: null,
    onToolbarPreparing: null,
    pager: { allowedPageSizes: 'auto', displayMode: 'adaptive', infoText: 'Page {0} of {1} ({2} items)', label: 'Page Navigation', showInfo: false, showNavigationButtons: false, showPageSizeSelector: false, visible: 'auto' },
    paging: { enabled: true, pageIndex: 0, pageSize: 20 },
    remoteOperations: 'auto',
    renderAsync: false,
    repaintChangesOnly: false,
    rowAlternationEnabled: false,
    rowDragging: { allowDropInsideItem: false, allowReordering: false, autoScroll: true, boundary: null, container: null, cursorOffset: null, data: null, dragDirection: 'both', dragTemplate: null, dropFeedbackMode: 'push', filter: '.dx-row', group: null, handle: '', onAdd: null, onDragChange: null, onDragEnd: null, onDragMove: null, onDragStart: null, onRemove: null, onReorder: null, scrollSensitivity: 60, scrollSpeed: 30, showDragIcons: true },
    scrolling: { columnRenderingMode: 'standard', mode: 'standard', preloadEnabled: false, renderAsync: 'auto', rowRenderingMode: 'standard', scrollByContent: false, scrollByThumb: false, showScrollbar: 'onHover', useNative: 'auto' },
    searchPanel: { highlightCaseSensitive: false, highlightSearchText: true, placeholder: 'Search...', searchVisibleColumnsOnly: false, text: '', visible: false, width: 160 },
    selectedRowKeys: [],
    selection: { allowSelectAll: true, deferred: false, mode: 'none', selectAllMode: 'allPages', showCheckBoxesMode: 'onClick' },
    showBorders: false,
    showColumnHeaders: true,
    showColumnLines: true,
    showRowLines: false,
    sorting: { ascendingText: 'Sort Ascending', clearText: 'Clear Sorting', descendingText: 'Sort Descending', mode: 'single', showSortIndexes: true },
    stateStoring: { customLoad: null, customSave: null, enabled: false, savingTimeout: 2000, storageKey: null, type: 'localStorage' },
    summary: { calculateCustomSummary: null, groupItems: [], recalculateWhileEditing: false, skipEmptyValues: true, texts: {}, totalItems: [] },
    syncLookupFilterValues: true,
    toolbar: null,
    twoWayBindingEnabled: true,
    width: undefined,
    wordWrapEnabled: false,
  },

  TreeList: {
    allowColumnReordering: false,
    allowColumnResizing: false,
    autoExpandAll: false,
    cacheEnabled: true,
    cellHintEnabled: true,
    columnAutoWidth: false,
    columnChooser: { allowSearch: false, emptyPanelText: 'Drag a column to the columns area', enabled: false, height: 350, mode: 'dragAndDrop', searchTimeout: 500, title: 'Column Chooser', width: 250 },
    columnFixing: { enabled: false },
    columnHidingEnabled: false,
    columnMinWidth: undefined,
    columnResizingMode: 'nextColumn',
    columnWidth: undefined,
    columns: [],
    customizeColumns: null,
    dataSource: null,
    editing: { allowAdding: false, allowDeleting: false, allowUpdating: false, confirmDelete: true, form: {}, mode: 'row', popup: {}, refreshMode: 'full', selectTextOnEditStart: false, startEditAction: 'click', texts: {}, useIcons: false },
    elementAttr: {},
    errorRowEnabled: true,
    expandedRowKeys: [],
    expandNodesOnFiltering: true,
    filterMode: 'withAncestors',
    filterRow: { applyFilter: 'auto', visible: false },
    filterSyncEnabled: 'auto',
    filterValue: null,
    focusedColumnIndex: -1,
    focusedRowEnabled: false,
    focusedRowIndex: -1,
    focusedRowKey: null,
    hasItemsExpr: 'hasItems',
    headerFilter: { visible: false },
    height: undefined,
    highlightChanges: false,
    hoverStateEnabled: false,
    itemsExpr: 'items',
    keyboardNavigation: { editOnKeyPress: false, enabled: true, enterKeyAction: 'startEdit', enterKeyDirection: 'none' },
    keyExpr: 'id',
    loadPanel: { enabled: 'auto', height: 90, showIndicator: true, showPane: true, text: 'Loading...', width: 200 },
    noDataText: 'No data',
    onCellClick: null,
    onCellDblClick: null,
    onCellHoverChanged: null,
    onCellPrepared: null,
    onContentReady: null,
    onContextMenuPreparing: null,
    onDisposing: null,
    onEditingStart: null,
    onEditorPrepared: null,
    onEditorPreparing: null,
    onFocusedCellChanged: null,
    onFocusedRowChanged: null,
    onInitialized: null,
    onInitNewRow: null,
    onKeyDown: null,
    onNodesInitialized: null,
    onOptionChanged: null,
    onRowClick: null,
    onRowCollapsed: null,
    onRowCollapsing: null,
    onRowDblClick: null,
    onRowExpanded: null,
    onRowExpanding: null,
    onRowInserted: null,
    onRowInserting: null,
    onRowPrepared: null,
    onRowRemoved: null,
    onRowRemoving: null,
    onRowUpdated: null,
    onRowUpdating: null,
    onRowValidating: null,
    onSaved: null,
    onSaving: null,
    onSelectionChanged: null,
    onToolbarPreparing: null,
    pager: { allowedPageSizes: 'auto', displayMode: 'adaptive', showInfo: false, showNavigationButtons: false, showPageSizeSelector: false, visible: 'auto' },
    paging: { enabled: false, pageIndex: 0, pageSize: 20 },
    parentIdExpr: 'parentId',
    remoteOperations: { filtering: false, grouping: false, sorting: false },
    renderAsync: false,
    repaintChangesOnly: false,
    rootValue: 0,
    rowAlternationEnabled: false,
    rowDragging: { allowDropInsideItem: true, allowReordering: false, autoScroll: true, dragDirection: 'both', dropFeedbackMode: 'push', onAdd: null, onDragEnd: null, onDragMove: null, onDragStart: null, onRemove: null, onReorder: null, showDragIcons: true },
    scrolling: { mode: 'standard', showScrollbar: 'onHover', useNative: 'auto' },
    searchPanel: { highlightCaseSensitive: false, highlightSearchText: true, placeholder: 'Search...', searchVisibleColumnsOnly: false, text: '', visible: false, width: 160 },
    selectedRowKeys: [],
    selection: { allowSelectAll: true, mode: 'none', recursive: false, selectAllMode: 'allPages', showCheckBoxesMode: 'onClick' },
    showBorders: false,
    showColumnHeaders: true,
    showColumnLines: true,
    showRowLines: false,
    sorting: { mode: 'single' },
    stateStoring: { enabled: false, savingTimeout: 2000, storageKey: null, type: 'localStorage' },
    toolbar: null,
    width: undefined,
    wordWrapEnabled: false,
  },

  List: {
    accessKey: null,
    activeStateEnabled: true,
    allowItemDeleting: false,
    bounceEnabled: true,
    collapsibleGroups: false,
    dataSource: null,
    disabled: false,
    displayExpr: null,
    elementAttr: {},
    focusStateEnabled: true,
    grouped: false,
    groupTemplate: null,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    indicateLoading: true,
    itemDeleteMode: 'toggle',
    itemDragging: { allowDropInsideItem: false, allowReordering: false, autoScroll: true, boundary: null, container: null, cursorOffset: null, data: null, dragDirection: 'vertical', dragTemplate: null, dropFeedbackMode: 'push', filter: '.dx-item', group: null, handle: '', onAdd: null, onDragChange: null, onDragEnd: null, onDragMove: null, onDragStart: null, onRemove: null, onReorder: null, scrollSensitivity: 60, scrollSpeed: 30, showDragIcons: true },
    items: [],
    itemTemplate: null,
    keyExpr: null,
    menuItems: [],
    menuMode: 'context',
    nextButtonText: 'More',
    noDataText: 'No data',
    onContentReady: null,
    onDisposing: null,
    onGroupRendered: null,
    onInitialized: null,
    onItemClick: null,
    onItemContextMenu: null,
    onItemDeleted: null,
    onItemDeleting: null,
    onItemHold: null,
    onItemRendered: null,
    onItemReordered: null,
    onItemSwipe: null,
    onOptionChanged: null,
    onPageLoading: null,
    onPullRefresh: null,
    onScroll: null,
    onSelectAllValueChanged: null,
    onSelectionChanged: null,
    pageLoadingText: 'Loading...',
    pageLoadMode: 'scrollBottom',
    pulledDownText: 'Release to refresh...',
    pullingDownText: 'Pull down to refresh...',
    pullRefreshEnabled: false,
    refreshingText: 'Refreshing...',
    repaintChangesOnly: false,
    rtlEnabled: false,
    scrollByContent: true,
    scrollByThumb: false,
    scrollingEnabled: true,
    searchEditorOptions: {},
    searchEnabled: false,
    searchExpr: null,
    searchMode: 'contains',
    searchTimeout: 500,
    searchValue: '',
    selectAllMode: 'page',
    selectAllText: 'Select All',
    selectedItemKeys: [],
    selectedItems: [],
    selectionMode: 'none',
    showScrollbar: 'onScroll',
    showSelectionControls: false,
    tabIndex: 0,
    useNativeScrolling: false,
    visible: true,
    width: undefined,
  },

  TreeView: {
    accessKey: null,
    activeStateEnabled: false,
    animationEnabled: true,
    checkboxMode: 'none',
    collapseIcon: null,
    createChildren: null,
    dataSource: null,
    dataStructure: 'tree',
    disabled: false,
    disabledExpr: 'disabled',
    displayExpr: 'text',
    elementAttr: {},
    expandAllEnabled: false,
    expandedExpr: 'expanded',
    expandEvent: 'dblclick',
    expandNodesRecursive: true,
    focusStateEnabled: false,
    hasItemsExpr: 'hasItems',
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    itemHoldTimeout: 750,
    items: [],
    itemTemplate: null,
    keyExpr: 'id',
    noDataText: 'No data',
    onContentReady: null,
    onDisposing: null,
    onInitialized: null,
    onItemClick: null,
    onItemCollapsed: null,
    onItemContextMenu: null,
    onItemExpanded: null,
    onItemHold: null,
    onItemRendered: null,
    onItemSelectionChanged: null,
    onOptionChanged: null,
    onSelectAllValueChanged: null,
    onSelectionChanged: null,
    parentIdExpr: 'parentId',
    rtlEnabled: false,
    scrollDirection: 'vertical',
    searchEditorOptions: {},
    searchEnabled: false,
    searchExpr: null,
    searchMode: 'contains',
    searchTimeout: 500,
    searchValue: '',
    selectAllText: 'Select All',
    selectByClick: false,
    selectedExpr: 'selected',
    selectedItem: null,
    selectedItemKeys: [],
    selectedItems: [],
    selectionMode: 'multiple',
    selectNodesRecursive: true,
    showCheckBoxesMode: 'none',
    tabIndex: 0,
    useNativeScrolling: false,
    virtualModeEnabled: false,
    visible: true,
    width: undefined,
  },

  Gallery: {
    accessKey: null,
    activeStateEnabled: false,
    animationDuration: 400,
    animationEnabled: true,
    dataSource: null,
    disabled: false,
    elementAttr: {},
    focusStateEnabled: false,
    height: 300,
    hint: undefined,
    hoverStateEnabled: false,
    indicatorEnabled: true,
    initialItemWidth: undefined,
    itemMargin: 10,
    items: [],
    itemTemplate: null,
    loop: false,
    noDataText: 'No data',
    onContentReady: null,
    onDisposing: null,
    onInitialized: null,
    onItemClick: null,
    onItemContextMenu: null,
    onItemHold: null,
    onItemRendered: null,
    onOptionChanged: null,
    onSelectionChanged: null,
    rtlEnabled: false,
    selectedIndex: 0,
    selectedItem: null,
    showIndicator: true,
    showNavButtons: false,
    slideshowDelay: 0,
    stretchImages: false,
    swipeEnabled: true,
    tabIndex: 0,
    visible: true,
    width: undefined,
    wrapAround: false,
  },

  // ─── EDITORS ──────────────────────────────────────────────────────────────

  TextBox: {
    accessKey: null,
    activeStateEnabled: true,
    buttons: [],
    disabled: false,
    elementAttr: {},
    focusStateEnabled: true,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    inputAttr: {},
    isDirty: false,
    isValid: true,
    label: '',
    labelMode: 'static',
    mask: '',
    maskChar: '_',
    maskInvalidMessage: 'Value does not match pattern',
    maskRules: {},
    maxLength: null,
    mode: 'text',
    name: '',
    onChangeHandler: null,
    onContentReady: null,
    onCopy: null,
    onCut: null,
    onDisposing: null,
    onEnterKey: null,
    onFocusIn: null,
    onFocusOut: null,
    onInitialized: null,
    onInput: null,
    onKeyDown: null,
    onKeyUp: null,
    onOptionChanged: null,
    onPaste: null,
    onValueChanged: null,
    placeholder: '',
    readOnly: false,
    rtlEnabled: false,
    showClearButton: false,
    showMaskMode: 'always',
    spellcheck: false,
    stylingMode: 'outlined',
    tabIndex: 0,
    text: undefined,
    useMaskedValue: false,
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: '',
    valueChangeEvent: 'change',
    visible: true,
    width: undefined,
  },

  TextArea: {
    accessKey: null,
    activeStateEnabled: true,
    autoResizeEnabled: false,
    buttons: [],
    disabled: false,
    elementAttr: {},
    focusStateEnabled: true,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    inputAttr: {},
    isDirty: false,
    isValid: true,
    label: '',
    labelMode: 'static',
    maxHeight: null,
    maxLength: null,
    minHeight: null,
    name: '',
    onContentReady: null,
    onDisposing: null,
    onEnterKey: null,
    onFocusIn: null,
    onFocusOut: null,
    onInitialized: null,
    onInput: null,
    onKeyDown: null,
    onKeyUp: null,
    onOptionChanged: null,
    onValueChanged: null,
    placeholder: '',
    readOnly: false,
    rtlEnabled: false,
    showClearButton: false,
    spellcheck: false,
    stylingMode: 'outlined',
    tabIndex: 0,
    text: undefined,
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: '',
    valueChangeEvent: 'change',
    visible: true,
    width: undefined,
  },

  NumberBox: {
    accessKey: null,
    activeStateEnabled: true,
    buttons: [],
    disabled: false,
    elementAttr: {},
    focusStateEnabled: true,
    format: '',
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    inputAttr: {},
    isDirty: false,
    isValid: true,
    label: '',
    labelMode: 'static',
    max: undefined,
    min: undefined,
    mode: 'text',
    name: '',
    onContentReady: null,
    onDisposing: null,
    onInitialized: null,
    onKeyDown: null,
    onKeyUp: null,
    onOptionChanged: null,
    onValueChanged: null,
    placeholder: '',
    readOnly: false,
    rtlEnabled: false,
    showClearButton: false,
    showSpinButtons: false,
    spellcheck: false,
    step: 1,
    stylingMode: 'outlined',
    tabIndex: 0,
    useLargeSpinButtons: true,
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: null,
    valueChangeEvent: 'change',
    visible: true,
    width: undefined,
  },

  CheckBox: {
    accessKey: null,
    activeStateEnabled: true,
    disabled: false,
    elementAttr: {},
    enableThreeStateBehavior: false,
    focusStateEnabled: true,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    iconSize: undefined,
    isDirty: false,
    isValid: true,
    name: '',
    onContentReady: null,
    onDisposing: null,
    onInitialized: null,
    onOptionChanged: null,
    onValueChanged: null,
    readOnly: false,
    rtlEnabled: false,
    tabIndex: 0,
    text: '',
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: false,
    visible: true,
    width: undefined,
  },

  SelectBox: {
    acceptCustomValue: false,
    accessKey: null,
    activeStateEnabled: true,
    buttons: [],
    dataSource: null,
    deferRendering: true,
    disabled: false,
    displayExpr: null,
    displayValue: undefined,
    dropDownButtonTemplate: 'dropDownButton',
    dropDownOptions: {},
    elementAttr: {},
    fieldTemplate: null,
    focusStateEnabled: true,
    grouped: false,
    groupTemplate: 'group',
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    inputAttr: {},
    isDirty: false,
    isValid: true,
    items: [],
    itemTemplate: 'item',
    label: '',
    labelMode: 'static',
    minSearchLength: 0,
    name: '',
    noDataText: 'No data',
    onChangeHandler: null,
    onClosed: null,
    onContentReady: null,
    onCustomItemCreating: null,
    onDisposing: null,
    onFocusIn: null,
    onFocusOut: null,
    onInitialized: null,
    onItemClick: null,
    onKeyDown: null,
    onKeyUp: null,
    onOpenedChanged: null,
    onOptionChanged: null,
    onSelectionChanged: null,
    onValueChanged: null,
    opened: false,
    openOnFieldClick: false,
    placeholder: 'Select...',
    readOnly: false,
    rtlEnabled: false,
    searchEnabled: false,
    searchExpr: null,
    searchMode: 'contains',
    searchTimeout: 500,
    searchValue: '',
    showClearButton: false,
    showDataBeforeSearch: false,
    showDropDownButton: true,
    showSelectionControls: false,
    stylingMode: 'outlined',
    tabIndex: 0,
    useItemTextAsTitle: false,
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: null,
    valueChangeEvent: 'change',
    valueExpr: null,
    visible: true,
    width: undefined,
    wrapItemText: false,
  },

  TagBox: {
    acceptCustomValue: false,
    accessKey: null,
    activeStateEnabled: true,
    applyValueMode: 'instantly',
    buttons: [],
    dataSource: null,
    deferRendering: true,
    disabled: false,
    displayExpr: null,
    dropDownButtonTemplate: 'dropDownButton',
    dropDownOptions: {},
    elementAttr: {},
    fieldTemplate: null,
    focusStateEnabled: true,
    grouped: false,
    groupTemplate: 'group',
    height: undefined,
    hideSelectedItems: false,
    hint: undefined,
    hoverStateEnabled: true,
    inputAttr: {},
    isDirty: false,
    isValid: true,
    items: [],
    itemTemplate: 'item',
    label: '',
    labelMode: 'static',
    maxDisplayedTags: undefined,
    maxFilterQueryLength: 1500,
    minSearchLength: 0,
    multiline: true,
    name: '',
    noDataText: 'No data',
    onChangeHandler: null,
    onClosed: null,
    onContentReady: null,
    onCustomItemCreating: null,
    onDisposing: null,
    onFocusIn: null,
    onFocusOut: null,
    onInitialized: null,
    onKeyDown: null,
    onKeyUp: null,
    onMultiTagPreparing: null,
    onOpenedChanged: null,
    onOptionChanged: null,
    onSelectAllValueChanged: null,
    onSelectionChanged: null,
    onValueChanged: null,
    opened: false,
    openOnFieldClick: false,
    placeholder: '',
    readOnly: false,
    rtlEnabled: false,
    searchEnabled: true,
    searchExpr: null,
    searchMode: 'contains',
    searchTimeout: 500,
    selectAllMode: 'page',
    selectAllText: 'Select All',
    selectedItems: [],
    showClearButton: false,
    showDataBeforeSearch: false,
    showDropDownButton: true,
    showMultiTagOnly: true,
    showSelectionControls: false,
    stylingMode: 'outlined',
    tabIndex: 0,
    tagTemplate: 'tag',
    useItemTextAsTitle: false,
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: [],
    valueChangeEvent: 'change',
    valueExpr: null,
    visible: true,
    width: undefined,
    wrapItemText: false,
  },

  Lookup: {
    accessKey: null,
    activeStateEnabled: true,
    applyButtonText: 'OK',
    applyValueMode: 'instantly',
    cancelButtonText: 'Cancel',
    cleanSearchOnOpening: true,
    clearButtonText: 'Clear',
    closeOnOutsideClick: false,
    dataSource: null,
    disabled: false,
    displayExpr: null,
    dropDownCentered: false,
    dropDownOptions: {},
    elementAttr: {},
    fieldTemplate: null,
    focusStateEnabled: true,
    fullScreen: false,
    grouped: false,
    groupTemplate: 'group',
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    isDirty: false,
    isValid: true,
    items: [],
    itemTemplate: 'item',
    label: '',
    labelMode: 'static',
    minSearchLength: 0,
    name: '',
    nextButtonText: 'More',
    noDataText: 'No data',
    onClosed: null,
    onContentReady: null,
    onDisposing: null,
    onInitialized: null,
    onItemClick: null,
    onOpenedChanged: null,
    onOptionChanged: null,
    onPageLoading: null,
    onPullRefresh: null,
    onScroll: null,
    onSelectionChanged: null,
    onTitleRendered: null,
    onValueChanged: null,
    opened: false,
    pageLoadingText: 'Loading...',
    pageLoadMode: 'scrollBottom',
    placeholder: 'Select...',
    popupHeight: '85%',
    popupWidth: undefined,
    pulledDownText: 'Release to refresh...',
    pullingDownText: 'Pull down to refresh...',
    pullRefreshEnabled: false,
    readOnly: false,
    refreshingText: 'Refreshing...',
    rtlEnabled: false,
    searchEnabled: true,
    searchExpr: null,
    searchMode: 'contains',
    searchPlaceholder: 'Search',
    searchTimeout: 500,
    searchValue: '',
    showCancelButton: true,
    showClearButton: false,
    showDataBeforeSearch: false,
    stylingMode: 'outlined',
    tabIndex: 0,
    title: '',
    titleTemplate: 'title',
    useItemTextAsTitle: false,
    useNativeScrolling: true,
    usePopover: false,
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: null,
    valueChangeEvent: 'change',
    valueExpr: null,
    visible: true,
    width: undefined,
    wrapItemText: false,
  },

  Autocomplete: {
    accessKey: null,
    activeStateEnabled: true,
    buttons: [],
    dataSource: null,
    deferRendering: true,
    disabled: false,
    displayExpr: null,
    dropDownButtonTemplate: 'dropDownButton',
    dropDownOptions: {},
    elementAttr: {},
    fieldTemplate: null,
    focusStateEnabled: true,
    grouped: false,
    groupTemplate: 'group',
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    inputAttr: {},
    isDirty: false,
    isValid: true,
    items: [],
    itemTemplate: 'item',
    label: '',
    labelMode: 'static',
    maxItemCount: 10,
    minSearchLength: 1,
    name: '',
    noDataText: 'No data',
    onChangeHandler: null,
    onClosed: null,
    onContentReady: null,
    onDisposing: null,
    onFocusIn: null,
    onFocusOut: null,
    onInitialized: null,
    onItemClick: null,
    onKeyDown: null,
    onKeyUp: null,
    onOpenedChanged: null,
    onOptionChanged: null,
    onSelectionChanged: null,
    onValueChanged: null,
    opened: false,
    placeholder: '',
    readOnly: false,
    rtlEnabled: false,
    searchExpr: null,
    searchMode: 'startswith',
    searchTimeout: 200,
    showClearButton: false,
    showDataBeforeSearch: false,
    showDropDownButton: false,
    stylingMode: 'outlined',
    tabIndex: 0,
    useItemTextAsTitle: false,
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: '',
    valueChangeEvent: 'change',
    valueExpr: null,
    visible: true,
    width: undefined,
    wrapItemText: false,
  },

  DropDownBox: {
    acceptCustomValue: false,
    accessKey: null,
    activeStateEnabled: true,
    buttons: [],
    contentTemplate: null,
    dataSource: null,
    deferRendering: true,
    disabled: false,
    displayExpr: null,
    displayValueFormatter: null,
    dropDownButtonTemplate: 'dropDownButton',
    dropDownOptions: {},
    elementAttr: {},
    fieldTemplate: null,
    focusStateEnabled: true,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    inputAttr: {},
    isDirty: false,
    isValid: true,
    items: [],
    keyExpr: null,
    label: '',
    labelMode: 'static',
    name: '',
    onChangeHandler: null,
    onClosed: null,
    onContentReady: null,
    onDisposing: null,
    onFocusIn: null,
    onFocusOut: null,
    onInitialized: null,
    onKeyDown: null,
    onKeyUp: null,
    onOpenedChanged: null,
    onOptionChanged: null,
    onValueChanged: null,
    opened: false,
    openOnFieldClick: false,
    placeholder: '',
    readOnly: false,
    rtlEnabled: false,
    showClearButton: false,
    showDropDownButton: true,
    stylingMode: 'outlined',
    tabIndex: 0,
    useItemTextAsTitle: false,
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: null,
    valueChangeEvent: 'change',
    valueExpr: null,
    visible: true,
    width: undefined,
  },

  DateBox: {
    acceptCustomValue: true,
    accessKey: null,
    activeStateEnabled: true,
    adaptivityEnabled: false,
    applyButtonText: 'OK',
    applyValueMode: 'instantly',
    buttons: [],
    calendarOptions: {},
    cancelButtonText: 'Cancel',
    dateOutOfRangeMessage: 'Value is out of range',
    dateSerializationFormat: null,
    deferRendering: true,
    disabled: false,
    disabledDates: null,
    displayFormat: null,
    dropDownButtonTemplate: 'dropDownButton',
    dropDownOptions: {},
    elementAttr: {},
    fieldTemplate: null,
    focusStateEnabled: true,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    inputAttr: {},
    interval: 30,
    invalidDateMessage: 'Value must be a date or time',
    isDirty: false,
    isValid: true,
    label: '',
    labelMode: 'static',
    max: undefined,
    maxZoomLevel: 'month',
    min: undefined,
    minZoomLevel: 'century',
    name: '',
    onChange: null,
    onClosed: null,
    onContentReady: null,
    onDisposing: null,
    onFocusIn: null,
    onFocusOut: null,
    onInitialized: null,
    onKeyDown: null,
    onKeyUp: null,
    onOpenedChanged: null,
    onOptionChanged: null,
    onValueChanged: null,
    opened: false,
    openOnFieldClick: true,
    pickerType: 'calendar',
    placeholder: '',
    readOnly: false,
    rtlEnabled: false,
    showAnalogClock: true,
    showClearButton: false,
    showDropDownButton: true,
    showTodayButton: false,
    spellcheck: false,
    stylingMode: 'outlined',
    tabIndex: 0,
    text: undefined,
    todayButtonText: 'Today',
    type: 'date',
    useMaskBehavior: false,
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: null,
    valueChangeEvent: 'change',
    visible: true,
    width: undefined,
  },

  DateRangeBox: {
    acceptCustomValue: true,
    accessKey: null,
    activeStateEnabled: true,
    applyButtonText: 'OK',
    applyValueMode: 'instantly',
    buttons: [],
    calendarOptions: {},
    cancelButtonText: 'Cancel',
    dateOutOfRangeMessage: 'Value is out of range',
    dateSerializationFormat: null,
    deferRendering: true,
    disabled: false,
    disabledDates: null,
    displayFormat: null,
    dropDownButtonTemplate: 'dropDownButton',
    dropDownOptions: {},
    elementAttr: {},
    endDate: null,
    endDateInputAttr: {},
    endDateLabel: 'End Date',
    endDateName: '',
    endDateOutOfRangeMessage: 'End value is out of range',
    endDatePlaceholder: '',
    endDateText: undefined,
    focusStateEnabled: true,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    isDirty: false,
    isValid: true,
    labelMode: 'static',
    max: undefined,
    min: undefined,
    multiView: true,
    onClosed: null,
    onContentReady: null,
    onDisposing: null,
    onInitialized: null,
    onOpenedChanged: null,
    onOptionChanged: null,
    onValueChanged: null,
    opened: false,
    openOnFieldClick: true,
    readOnly: false,
    rtlEnabled: false,
    showClearButton: false,
    showDropDownButton: true,
    showTodayButton: false,
    spellcheck: false,
    startDate: null,
    startDateInputAttr: {},
    startDateLabel: 'Start Date',
    startDateName: '',
    startDateOutOfRangeMessage: 'Start value is out of range',
    startDatePlaceholder: '',
    startDateText: undefined,
    stylingMode: 'outlined',
    tabIndex: 0,
    todayButtonText: 'Today',
    useMaskBehavior: false,
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: [null, null],
    visible: true,
    width: undefined,
  },

  ColorBox: {
    acceptCustomValue: false,
    accessKey: null,
    activeStateEnabled: true,
    applyButtonText: 'OK',
    applyValueMode: 'instantly',
    buttons: [],
    cancelButtonText: 'Cancel',
    disabled: false,
    dropDownButtonTemplate: 'dropDownButton',
    dropDownOptions: {},
    editAlphaChannel: false,
    elementAttr: {},
    fieldTemplate: null,
    focusStateEnabled: true,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    inputAttr: {},
    isDirty: false,
    isValid: true,
    keyStep: 1,
    label: '',
    labelMode: 'static',
    name: '',
    onChangeHandler: null,
    onClosed: null,
    onContentReady: null,
    onDisposing: null,
    onFocusIn: null,
    onFocusOut: null,
    onInitialized: null,
    onKeyDown: null,
    onKeyUp: null,
    onOpenedChanged: null,
    onOptionChanged: null,
    onValueChanged: null,
    opened: false,
    openOnFieldClick: true,
    placeholder: '',
    readOnly: false,
    rtlEnabled: false,
    showClearButton: false,
    showDropDownButton: true,
    stylingMode: 'outlined',
    tabIndex: 0,
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: null,
    valueChangeEvent: 'change',
    visible: true,
    width: undefined,
  },

  Slider: {
    accessKey: null,
    activeStateEnabled: true,
    disabled: false,
    elementAttr: {},
    focusStateEnabled: true,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    isDirty: false,
    isValid: true,
    keyStep: 1,
    label: { format: null, position: 'end', visible: false },
    max: 100,
    min: 0,
    name: '',
    onContentReady: null,
    onDisposing: null,
    onInitialized: null,
    onOptionChanged: null,
    onValueChanged: null,
    readOnly: false,
    rtlEnabled: false,
    showRange: true,
    step: 1,
    stylingMode: 'outlined',
    tabIndex: 0,
    tooltip: { enabled: false, format: null, position: 'top', showMode: 'onHover' },
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: 50,
    valueChangeMode: 'onHandleMove',
    visible: true,
    width: undefined,
  },

  RangeSlider: {
    accessKey: null,
    activeStateEnabled: true,
    disabled: false,
    elementAttr: {},
    end: 100,
    focusStateEnabled: true,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    isDirty: false,
    isValid: true,
    keyStep: 1,
    label: { format: null, position: 'end', visible: false },
    max: 100,
    min: 0,
    name: '',
    onContentReady: null,
    onDisposing: null,
    onInitialized: null,
    onOptionChanged: null,
    onValueChanged: null,
    readOnly: false,
    rtlEnabled: false,
    start: 0,
    step: 1,
    stylingMode: 'outlined',
    tabIndex: 0,
    tooltip: { enabled: false, format: null, position: 'top', showMode: 'onHover' },
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: [0, 100],
    valueChangeMode: 'onHandleMove',
    visible: true,
    width: undefined,
  },

  Switch: {
    accessKey: null,
    activeStateEnabled: true,
    disabled: false,
    elementAttr: {},
    focusStateEnabled: true,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    isDirty: false,
    isValid: true,
    name: '',
    onContentReady: null,
    onDisposing: null,
    onInitialized: null,
    onOptionChanged: null,
    onValueChanged: null,
    readOnly: false,
    rtlEnabled: false,
    switchedOffText: 'OFF',
    switchedOnText: 'ON',
    tabIndex: 0,
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: false,
    visible: true,
    width: undefined,
  },

  RadioGroup: {
    accessKey: null,
    activeStateEnabled: true,
    dataSource: null,
    disabled: false,
    displayExpr: null,
    elementAttr: {},
    focusStateEnabled: true,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    isDirty: false,
    isValid: true,
    items: [],
    itemTemplate: 'item',
    layout: 'vertical',
    name: '',
    onContentReady: null,
    onDisposing: null,
    onInitialized: null,
    onOptionChanged: null,
    onValueChanged: null,
    readOnly: false,
    rtlEnabled: false,
    tabIndex: 0,
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: null,
    valueExpr: null,
    visible: true,
    width: undefined,
  },

  ButtonGroup: {
    accessKey: null,
    activeStateEnabled: true,
    disabled: false,
    elementAttr: {},
    focusStateEnabled: true,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    items: [],
    itemTemplate: null,
    keyExpr: null,
    onContentReady: null,
    onDisposing: null,
    onInitialized: null,
    onItemClick: null,
    onOptionChanged: null,
    onSelectionChanged: null,
    rtlEnabled: false,
    selectedItemKeys: [],
    selectedItems: [],
    selectionMode: 'single',
    stylingMode: 'contained',
    tabIndex: 0,
    visible: true,
    width: undefined,
  },

  Calendar: {
    accessKey: null,
    activeStateEnabled: true,
    cellTemplate: 'cell',
    dateSerializationFormat: null,
    disabled: false,
    disabledDates: null,
    elementAttr: {},
    firstDayOfWeek: 0,
    focusStateEnabled: true,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    isDirty: false,
    isValid: true,
    max: undefined,
    maxZoomLevel: 'month',
    min: undefined,
    minZoomLevel: 'century',
    name: '',
    onCellClick: null,
    onContoentReady: null,
    onDisposing: null,
    onInitialized: null,
    onOptionChanged: null,
    onValueChanged: null,
    readOnly: false,
    rtlEnabled: false,
    selectionMode: 'single',
    showOtherMonthDays: true,
    showTodayButton: false,
    showWeekNumbers: false,
    tabIndex: 0,
    todayButtonText: 'Today',
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: null,
    visible: true,
    weekNumberRule: 'auto',
    width: undefined,
    zoomLevel: 'month',
  },

  HtmlEditor: {
    accessKey: null,
    activeStateEnabled: true,
    allowSoftLineBreak: false,
    customizeModules: null,
    disabled: false,
    elementAttr: {},
    focusStateEnabled: true,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    imageUpload: { fileUploadMode: 'base64', fileUploaderOptions: {}, tabs: ['url'], uploadDirectory: null, uploadUrl: null },
    isDirty: false,
    isValid: true,
    label: '',
    labelMode: 'static',
    mediaResizing: { enabled: false },
    mentions: [],
    name: '',
    onContentReady: null,
    onDisposing: null,
    onFocusIn: null,
    onFocusOut: null,
    onInitialized: null,
    onOptionChanged: null,
    onValueChanged: null,
    placeholder: '',
    readOnly: false,
    rtlEnabled: false,
    stylingMode: 'outlined',
    tabIndex: 0,
    tableContextMenu: { enabled: false },
    tableResizing: { enabled: false },
    toolbar: { items: ['bold','italic','underline','separator','alignLeft','alignCenter','alignRight','separator','orderedList','bulletList'] },
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: null,
    valueType: 'html',
    visible: true,
    width: undefined,
  },

  FileUploader: {
    abortUpload: null,
    accept: '',
    accessKey: null,
    activeStateEnabled: true,
    allowCanceling: true,
    allowedFileExtensions: [],
    chunkSize: 0,
    dialogTrigger: undefined,
    disabled: false,
    dropZone: undefined,
    elementAttr: {},
    focusStateEnabled: true,
    height: undefined,
    hint: undefined,
    hoverStateEnabled: true,
    inputAttr: {},
    invalidFileExtensionMessage: 'File type is not allowed',
    invalidMaxFileSizeMessage: 'File is too large',
    invalidMinFileSizeMessage: 'File is too small',
    isValid: true,
    labelText: 'or Drop file here',
    maxFileSize: 0,
    minFileSize: 0,
    multiple: false,
    name: 'files[]',
    onBeforeSend: null,
    onContentReady: null,
    onDisposing: null,
    onDropZoneEnter: null,
    onDropZoneLeave: null,
    onFilesUploaded: null,
    onInitialized: null,
    onOptionChanged: null,
    onProgress: null,
    onUploadAborted: null,
    onUploaded: null,
    onUploadError: null,
    onUploadStarted: null,
    onValueChanged: null,
    progress: 0,
    readOnly: false,
    readyToUploadMessage: 'Ready to upload',
    rtlEnabled: false,
    selectButtonText: 'Select File',
    showFileList: true,
    tabIndex: 0,
    uploadAbortedMessage: 'Upload cancelled',
    uploadButtonText: 'Upload',
    uploadChunk: null,
    uploadedMessage: 'Uploaded',
    uploadFailedMessage: 'Upload failed',
    uploadFile: null,
    uploadHeaders: {},
    uploadMethod: 'POST',
    uploadMode: 'instantly',
    uploadUrl: '/',
    validationError: null,
    validationErrors: null,
    validationMessageMode: 'auto',
    validationMessagePosition: 'auto',
    validationStatus: 'valid',
    value: [],
    visible: true,
    width: undefined,
  },

  Form: {
    accessKey: null,
    activeStateEnabled: false,
    alignItemLabels: true,
    alignItemLabelsInAllGroups: true,
    colCount: 1,
    colCountByScreen: { lg: null, md: null, sm: null, xs: 1 },
    customizeItem: null,
    disabled: false,
    elementAttr: {},
    focusStateEnabled: false,
    formData: {},
    height: undefined,
    hint: undefined,
    hoverStateEnabled: false,
    isDirty: false,
    isValid: true,
    items: [],
    labelLocation: 'left',
    labelMode: 'outside',
    minColWidth: 200,
    onContentReady: null,
    onDisposing: null,
    onEditorEnterKey: null,
    onFieldDataChanged: null,
    onInitialized: null,
    onOptionChanged: null,
    optionalMark: 'optional',
    readOnly: false,
    requiredMark: '*',
    requiredMessage: '{0} is required',
    rtlEnabled: false,
    screenByWidth: null,
    scrollingEnabled: false,
    showColonAfterLabel: true,
    showOptionalMark: false,
    showRequiredMark: true,
    showValidationSummary: false,
    tabIndex: 0,
    validationGroup: undefined,
    visible: true,
    width: undefined,
  },

  // ─── CHARTS & VISUALIZATION (existing entries preserved) ──────────────────

  Chart: {
    adaptiveLayout: { enabled: true, height: 80, keepLabels: true, width: 80 },
    animation: { duration: 1000, easing: 'easeOutCubic', enabled: true, maxPointCountSupported: 300 },
    argumentAxis: { allowDecimals: true, color: '#767676', discreteAxisDivisionMode: 'betweenLabels', endOnTick: false, grid: { color: '#d3d3d3', visible: false, width: 1 }, inverted: false, label: { displayMode: 'standard', format: null, indentFromAxis: 10, overlappingBehavior: 'hide', position: 'outside', rotationAngle: 90, staggeringSpacing: 5, visible: true }, minorGrid: { color: '#d3d3d3', visible: false, width: 1 }, minorTick: { color: '#767676', length: 7, opacity: 0.3, visible: false, width: 1 }, offset: 0, position: 'bottom', tick: { color: '#767676', length: 8, visible: true, width: 1 }, title: { alignment: 'center', margin: 6, text: null }, type: 'continuous', valueMarginsEnabled: true, visible: true, width: 1 },
    commonSeriesSettings: { aggregation: { enabled: false, method: 'avg' }, color: null, dashStyle: 'solid', hoverMode: 'nearestPoint', label: {}, opacity: null, point: {}, selectionMode: 'includePoints', showInLegend: true, type: 'line', visible: true, width: 2 },
    crosshair: { color: '#f05b41', dashStyle: 'dot', enabled: false, opacity: null, width: 1 },
    dataSource: null,
    export: { backgroundColor: '#ffffff', enabled: false, fileName: 'file', formats: ['PNG','PDF','JPEG','SVG'], margin: 10 },
    legend: { backgroundColor: null, horizontalAlignment: 'right', hoverMode: 'includePoints', margin: 10, markerSize: 12, position: 'outside', verticalAlignment: 'top', visible: true },
    palette: 'Material',
    scrollBar: { color: null, offset: 5, position: 'top', visible: false, width: 10 },
    series: [],
    size: { height: null, width: null },
    title: { horizontalAlignment: 'center', margin: 10, text: null, verticalAlignment: 'top' },
    tooltip: { arrowLength: 10, color: '#ffffff', enabled: false, interactive: false, location: 'center', paddingLeftRight: 18, paddingTopBottom: 15, shared: false },
    zoomAndPan: { allowMouseWheel: false, allowTouchGestures: true, argumentAxis: 'none', dragToZoom: false, panKey: 'shift', valueAxis: 'none' },
  },

  PieChart: {
    animation: { duration: 1000, easing: 'easeOutCubic', enabled: true },
    commonSeriesSettings: { argumentField: 'arg', border: {}, hoverMode: 'onlyPoint', label: {}, selectionMode: 'onlyPoint', valueField: 'val', visible: true },
    dataSource: null,
    export: { enabled: false },
    innerRadius: 0,
    legend: { horizontalAlignment: 'right', hoverMode: 'allArgumentPoints', margin: 10, markerSize: 12, position: 'outside', verticalAlignment: 'top', visible: true },
    palette: 'Material',
    series: [],
    size: { height: null, width: null },
    startAngle: 0,
    title: { text: null },
    tooltip: { enabled: false },
    type: 'pie',
  },

  PolarChart: {
    animation: { duration: 1000, enabled: true },
    commonSeriesSettings: { closed: true, color: null, dashStyle: 'solid', type: 'scatter', visible: true, width: 2 },
    dataSource: null,
    export: { enabled: false },
    legend: { visible: true },
    palette: 'Material',
    series: [],
    size: { height: null, width: null },
    title: { text: null },
    tooltip: { enabled: false },
    useSpiderWeb: false,
  },

  Funnel: {
    algorithm: 'dynamicSlope',
    argumentField: 'arg',
    dataSource: null,
    export: { enabled: false },
    inverted: false,
    item: { border: { color: '#ffffff', visible: true, width: 2 } },
    label: { position: 'columns', visible: true },
    legend: { visible: false },
    neckHeight: 0,
    neckWidth: 0,
    palette: 'Material',
    resolveLabelOverlapping: 'shift',
    sortData: true,
    title: { text: null },
    tooltip: { enabled: false },
    valueField: 'val',
  },

  Sankey: {
    alignment: 'center',
    dataSource: null,
    export: { enabled: false },
    label: { visible: true },
    link: { colorMode: 'none', opacity: 0.3 },
    node: { padding: 30, width: 30 },
    palette: 'Material',
    sourceField: 'source',
    targetField: 'target',
    title: { text: null },
    tooltip: { enabled: false },
    weightField: 'weight',
  },

  TreeMap: {
    childrenField: 'items',
    colorizer: { colorizeGroups: false, palette: 'Material', type: null },
    dataSource: null,
    export: { enabled: false },
    group: { border: { color: '#d3d3d3', width: 1 }, color: '#eeeeee', headerHeight: null, padding: 4 },
    labelField: 'name',
    layoutAlgorithm: 'squarified',
    layoutDirection: 'leftTopRightBottom',
    maxDepth: null,
    title: { text: null },
    tooltip: { enabled: false },
    valueField: 'value',
  },

  VectorMap: {
    background: { borderColor: '#cacaca', color: '#ffffff' },
    bounds: null,
    center: null,
    controlBar: { enabled: true, margin: 20, opacity: 0.3, position: 'top-left' },
    export: { enabled: false },
    layers: [],
    legends: [],
    maxZoomFactor: 256,
    panningEnabled: true,
    projection: 'mercator',
    title: { text: null },
    tooltip: { enabled: false },
    zoomingEnabled: true,
  },

  Sparkline: {
    argumentField: 'arg',
    barNegativeColor: '#d7170b',
    barPositiveColor: '#a9a9a9',
    dataSource: null,
    firstLastColor: '#666666',
    lineColor: '#666666',
    lineWidth: 2,
    pointColor: '#ffffff',
    pointSize: 4,
    pointSymbol: 'circle',
    showFirstLast: true,
    showMinMax: false,
    size: { height: null, width: null },
    tooltip: { enabled: true },
    type: 'line',
    valueField: 'val',
  },

  Bullet: {
    color: '#e8c267',
    dataSource: null,
    endScaleValue: null,
    showTarget: true,
    showZeroLevel: true,
    size: { height: null, width: null },
    startScaleValue: 0,
    target: 0,
    targetColor: '#666666',
    targetWidth: 4,
    tooltip: { enabled: true },
    value: 0,
  },

  BarGauge: {
    animation: { duration: 1000, enabled: true },
    backgroundColor: '#e0e0e0',
    barSpacing: 4,
    endValue: 100,
    export: { enabled: false },
    geometry: { endAngle: 405, startAngle: 135 },
    label: { indent: 20, visible: true },
    palette: 'Material',
    relativeInnerRadius: 0.3,
    startValue: 0,
    title: { text: null },
    tooltip: { enabled: false },
    values: [],
  },

  LinearGauge: {
    animation: { duration: 1000, enabled: true },
    containerBackgroundColor: '#ffffff',
    export: { enabled: false },
    geometry: { orientation: 'vertical' },
    rangeContainer: { backgroundColor: '#808080', offset: 0, ranges: [], width: 5 },
    scale: { endValue: 100, label: {}, majorTick: {}, minorTick: {}, startValue: 0, type: 'continuous' },
    title: { text: null },
    tooltip: { enabled: false },
    value: null,
  },

  CircularGauge: {
    animation: { duration: 1000, enabled: true },
    containerBackgroundColor: '#ffffff',
    export: { enabled: false },
    geometry: { endAngle: 405, startAngle: 135 },
    rangeContainer: { backgroundColor: '#808080', orientation: 'outside', ranges: [], width: 5 },
    scale: { endValue: 100, label: {}, majorTick: {}, minorTick: {}, startValue: 0 },
    title: { text: null },
    tooltip: { enabled: false },
    value: null,
  },

  RangeSelector: {
    background: { color: '#ffffff', visible: true },
    behavior: { allowSlidersSwap: true, animationEnabled: true, callValueChanged: 'onMovingComplete', manualRangeSelectionEnabled: true, moveSelectedRangeByClick: true, snapToTicks: true },
    chart: { commonSeriesSettings: {}, palette: 'Material', series: [] },
    dataSource: null,
    export: { enabled: false },
    scale: { endValue: null, label: {}, startValue: null, tick: {}, type: null },
    selectedRangeColor: '#729ab4',
    title: { text: null },
    value: [null, null],
  },

  PivotGrid: {
    allowExpandAll: false,
    allowFiltering: false,
    allowSorting: false,
    allowSortingBySummary: false,
    columnAutoWidth: false,
    columnChooser: { enabled: false, height: 350, layout: 'tree', title: 'Column Chooser', width: 250 },
    dataSource: null,
    export: { enabled: false, fileName: 'PivotGrid' },
    fieldChooser: { enabled: true, height: 600, layout: 2, title: 'Field Chooser', width: 600 },
    fieldPanel: { allowFieldDragging: true, showColumnFields: true, showDataFields: true, showFilterFields: true, showRowFields: true, visible: false },
    scrolling: { mode: 'standard' },
    showBorders: false,
    showColumnGrandTotals: true,
    showColumnTotals: true,
    showRowGrandTotals: true,
    showRowTotals: true,
    wordWrapEnabled: false,
  },

};

export default WIDGET_CONFIGS;
