// widgetProperties.js
// The widget properties the Screens designer exposes, per widget: what the
// details panel shows, what can be bound (⚡), and what a newly dropped
// widget starts with. Read through designer/widgets/widgetPropertyDefs.js
// (getWidgetPropertyDefs), never directly — that's where the Widgets
// area's saved edits are layered on top.
//
// GENERATED by the Widgets area's Export (designer/widgets/
// widgetPropertiesSource.js). Hand edits are fine, but the next export
// rewrites the layout.
//
// A property: { name, label, type, options?, default, bindable?, group? }
//   name      the DevExtreme option; dot paths ('title.text') are expanded
//             into nested objects when the widget renders
//   type      bool | number | string | enum | color | data
//             ('data' is a collection — bind-only, no static editor)
//   options   the choices, for enum
//   bindable  false for options that name a column rather than hold a
//             value (argumentField, keyExpr…), so they can't be bound
//   group     optional heading in the details panel

const WIDGET_PROPERTIES = {

// ─── GRIDS & LISTS ─────────────────────────────────────────────────────────
DataGrid: [
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'showBorders', label: 'Show Borders', type: 'bool', default: false },
  { name: 'showRowLines', label: 'Show Row Lines', type: 'bool', default: false },
  { name: 'showColumnLines', label: 'Show Column Lines', type: 'bool', default: true },
  { name: 'showColumnHeaders', label: 'Column Headers', type: 'bool', default: true },
  { name: 'allowColumnReordering', label: 'Col Reordering', type: 'bool', default: false },
  { name: 'allowColumnResizing', label: 'Col Resizing', type: 'bool', default: false },
  { name: 'columnAutoWidth', label: 'Column Auto Width', type: 'bool', default: false },
  { name: 'hoverStateEnabled', label: 'Hover State', type: 'bool', default: false },
  { name: 'rowAlternationEnabled', label: 'Row Alternation', type: 'bool', default: false },
  { name: 'wordWrapEnabled', label: 'Word Wrap', type: 'bool', default: false },
  { name: 'pager.visible', label: 'Pager Visible', type: 'bool', default: true },
  { name: 'searchPanel.visible', label: 'Search Panel', type: 'bool', default: false },
  { name: 'filterRow.visible', label: 'Filter Row', type: 'bool', default: false },
  { name: 'groupPanel.visible', label: 'Group Panel', type: 'bool', default: false },
  { name: 'headerFilter.visible', label: 'Header Filter', type: 'bool', default: false },
  { name: 'selection.mode', label: 'Selection Mode', type: 'enum', options: ['none','single','multiple'], default: 'none' },
  { name: 'editing.mode', label: 'Edit Mode', type: 'enum', options: ['row','cell','batch','form','popup'], default: 'row' },
  { name: 'editing.allowAdding', label: 'Allow Adding', type: 'bool', default: false },
  { name: 'editing.allowUpdating', label: 'Allow Updating', type: 'bool', default: false },
  { name: 'editing.allowDeleting', label: 'Allow Deleting', type: 'bool', default: false },
  { name: 'scrolling.mode', label: 'Scrolling Mode', type: 'enum', options: ['standard','virtual','infinite'], default: 'standard' },
  { name: 'paging.pageSize', label: 'Page Size', type: 'number', default: 20 },
],

TreeList: [
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'showBorders', label: 'Show Borders', type: 'bool', default: false },
  { name: 'showRowLines', label: 'Show Row Lines', type: 'bool', default: false },
  { name: 'showColumnLines', label: 'Show Column Lines', type: 'bool', default: true },
  { name: 'allowColumnResizing', label: 'Col Resizing', type: 'bool', default: false },
  { name: 'autoExpandAll', label: 'Auto Expand All', type: 'bool', default: false },
  { name: 'hoverStateEnabled', label: 'Hover State', type: 'bool', default: false },
  { name: 'rowAlternationEnabled', label: 'Row Alternation', type: 'bool', default: false },
  { name: 'filterRow.visible', label: 'Filter Row', type: 'bool', default: false },
  { name: 'searchPanel.visible', label: 'Search Panel', type: 'bool', default: false },
  { name: 'selection.mode', label: 'Selection Mode', type: 'enum', options: ['none','single','multiple'], default: 'none' },
  { name: 'selection.recursive', label: 'Recursive Select', type: 'bool', default: false },
  { name: 'editing.mode', label: 'Edit Mode', type: 'enum', options: ['row','cell','batch','form','popup'], default: 'row' },
  { name: 'editing.allowAdding', label: 'Allow Adding', type: 'bool', default: false },
  { name: 'editing.allowUpdating', label: 'Allow Updating', type: 'bool', default: false },
  { name: 'editing.allowDeleting', label: 'Allow Deleting', type: 'bool', default: false },
  { name: 'scrolling.mode', label: 'Scrolling Mode', type: 'enum', options: ['standard','virtual'], default: 'standard' },
  { name: 'keyExpr', label: 'Key Expr', type: 'string', default: 'id', bindable: false },
  { name: 'parentIdExpr', label: 'Parent ID Expr', type: 'string', default: 'parentId', bindable: false },
],

List: [
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'selectionMode', label: 'Selection Mode', type: 'enum', options: ['none','single','multiple','all'], default: 'none' },
  { name: 'showSelectionControls', label: 'Selection Controls', type: 'bool', default: false },
  { name: 'searchEnabled', label: 'Search Enabled', type: 'bool', default: false },
  { name: 'allowItemDeleting', label: 'Allow Delete', type: 'bool', default: false },
  { name: 'allowItemReordering', label: 'Allow Reorder', type: 'bool', default: false },
  { name: 'grouped', label: 'Grouped', type: 'bool', default: false },
  { name: 'pullRefreshEnabled', label: 'Pull to Refresh', type: 'bool', default: false },
  { name: 'pageLoadMode', label: 'Page Load Mode', type: 'enum', options: ['scrollBottom','nextButton'], default: 'scrollBottom' },
  { name: 'showScrollbar', label: 'Show Scrollbar', type: 'enum', options: ['onScroll','onHover','always','never'], default: 'onScroll' },
  { name: 'noDataText', label: 'No Data Text', type: 'string', default: 'No data' },
],

TreeView: [
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'showCheckBoxesMode', label: 'Checkboxes', type: 'enum', options: ['none','normal','selectAll'], default: 'none' },
  { name: 'selectionMode', label: 'Selection Mode', type: 'enum', options: ['single','multiple'], default: 'multiple' },
  { name: 'searchEnabled', label: 'Search Enabled', type: 'bool', default: false },
  { name: 'expandAllEnabled', label: 'Expand All Button', type: 'bool', default: false },
  { name: 'selectByClick', label: 'Select by Click', type: 'bool', default: false },
  { name: 'selectNodesRecursive', label: 'Recursive Select', type: 'bool', default: true },
  { name: 'expandNodesRecursive', label: 'Recursive Expand', type: 'bool', default: true },
  { name: 'animationEnabled', label: 'Animation', type: 'bool', default: true },
  { name: 'dataStructure', label: 'Data Structure', type: 'enum', options: ['tree','plain'], default: 'tree' },
  { name: 'noDataText', label: 'No Data Text', type: 'string', default: 'No data' },
],

Gallery: [
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'loop', label: 'Loop', type: 'bool', default: false },
  { name: 'showIndicator', label: 'Show Indicator', type: 'bool', default: true },
  { name: 'showNavButtons', label: 'Nav Buttons', type: 'bool', default: false },
  { name: 'swipeEnabled', label: 'Swipe Enabled', type: 'bool', default: true },
  { name: 'stretchImages', label: 'Stretch Images', type: 'bool', default: false },
  { name: 'animationEnabled', label: 'Animation', type: 'bool', default: true },
  { name: 'animationDuration', label: 'Animation Duration', type: 'number', default: 400 },
  { name: 'slideshowDelay', label: 'Slideshow Delay', type: 'number', default: 0 },
  { name: 'wrapAround', label: 'Wrap Around', type: 'bool', default: false },
],

// ─── CHARTS & VISUALIZATION ────────────────────────────────────────────────
Chart: [
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'commonSeriesSettings.argumentField', label: 'Argument Field', type: 'string', default: 'timestamp', bindable: false },
  { name: 'commonSeriesSettings.valueField', label: 'Value Field', type: 'string', default: 'value', bindable: false },
  { name: 'seriesTemplate.nameField', label: 'Series Group Field', type: 'string', default: '', bindable: false },
  { name: 'palette', label: 'Palette', type: 'enum', options: ['Material','Soft Pastel','Harmony Light','Office','Vintage','Violet','Carmine','Dark Moon','Soft Blue','Dark Violet','Green Mist'], default: 'Material' },
  { name: 'legend.visible', label: 'Legend Visible', type: 'bool', default: true },
  { name: 'legend.position', label: 'Legend Position', type: 'enum', options: ['inside','outside'], default: 'outside' },
  { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
  { name: 'commonSeriesSettings.type', label: 'Series Type', type: 'enum', options: ['line','bar','area','spline','scatter','stepLine','fullStackedBar','stackedBar'], default: 'line' },
  { name: 'scrollBar.visible', label: 'Scroll Bar', type: 'bool', default: false },
  { name: 'zoomAndPan.argumentAxis', label: 'Zoom Argument Axis', type: 'enum', options: ['none','zoom','pan','both'], default: 'none' },
],

PieChart: [
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'palette', label: 'Palette', type: 'enum', options: ['Material','Soft Pastel','Harmony Light','Office','Vintage','Violet'], default: 'Material' },
  { name: 'legend.visible', label: 'Legend Visible', type: 'bool', default: true },
  { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
  { name: 'type', label: 'Type', type: 'enum', options: ['pie','donut'], default: 'pie' },
  { name: 'innerRadius', label: 'Inner Radius', type: 'number', default: 0.5 },
],

PolarChart: [
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'palette', label: 'Palette', type: 'enum', options: ['Material','Soft Pastel','Harmony Light','Office','Vintage','Violet'], default: 'Material' },
  { name: 'useSpiderWeb', label: 'Spider Web', type: 'bool', default: false },
  { name: 'commonSeriesSettings.type', label: 'Series Type', type: 'enum', options: ['line','area','bar','scatter','stackedLine','stackedArea','fullStackedLine','fullStackedArea'], default: 'scatter' },
  { name: 'legend.visible', label: 'Legend Visible', type: 'bool', default: true },
  { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
  { name: 'commonSeriesSettings.closed', label: 'Closed Series', type: 'bool', default: true },
],

Funnel: [
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'algorithm', label: 'Algorithm', type: 'enum', options: ['dynamicSlope','dynamicHeight'], default: 'dynamicSlope' },
  { name: 'palette', label: 'Palette', type: 'enum', options: ['Material','Soft Pastel','Harmony Light','Office','Vintage','Violet'], default: 'Material' },
  { name: 'inverted', label: 'Inverted', type: 'bool', default: false },
  { name: 'sortData', label: 'Sort Data', type: 'bool', default: true },
  { name: 'label.visible', label: 'Labels Visible', type: 'bool', default: true },
  { name: 'label.position', label: 'Label Position', type: 'enum', options: ['inside','outside','columns'], default: 'columns' },
  { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
  { name: 'resolveLabelOverlapping', label: 'Overlap Mode', type: 'enum', options: ['shift','hide','none'], default: 'shift' },
],

Sankey: [
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'palette', label: 'Palette', type: 'enum', options: ['Material','Soft Pastel','Harmony Light','Office','Vintage','Violet'], default: 'Material' },
  { name: 'alignment', label: 'Alignment', type: 'enum', options: ['top','center','bottom'], default: 'center' },
  { name: 'label.visible', label: 'Labels Visible', type: 'bool', default: true },
  { name: 'link.colorMode', label: 'Link Color Mode', type: 'enum', options: ['none','source','target','gradient'], default: 'none' },
  { name: 'link.opacity', label: 'Link Opacity', type: 'number', default: 0.3 },
  { name: 'node.width', label: 'Node Width', type: 'number', default: 30 },
  { name: 'node.padding', label: 'Node Padding', type: 'number', default: 30 },
  { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
],

TreeMap: [
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'palette', label: 'Palette', type: 'enum', options: ['Material','Soft Pastel','Harmony Light','Office','Vintage','Violet'], default: 'Material' },
  { name: 'layoutAlgorithm', label: 'Layout Algorithm', type: 'enum', options: ['squarified','strip','sliceanddice'], default: 'squarified' },
  { name: 'layoutDirection', label: 'Layout Direction', type: 'enum', options: ['leftTopRightBottom','leftBottomRightTop','rightTopLeftBottom','rightBottomLeftTop'], default: 'leftTopRightBottom' },
  { name: 'colorizer.type', label: 'Colorizer Type', type: 'enum', options: ['none','gradient','range','discrete'], default: 'none' },
  { name: 'colorizer.colorizeGroups', label: 'Colorize Groups', type: 'bool', default: false },
  { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
  { name: 'maxDepth', label: 'Max Depth', type: 'number', default: 2 },
  { name: 'resolveLabelOverlapping', label: 'Label Overlap', type: 'enum', options: ['hide','none'], default: 'hide' },
],

VectorMap: [
  { name: 'projection', label: 'Projection', type: 'enum', options: ['mercator','equirectangular','lambert','miller'], default: 'mercator' },
  { name: 'panningEnabled', label: 'Panning', type: 'bool', default: true },
  { name: 'zoomingEnabled', label: 'Zooming', type: 'bool', default: true },
  { name: 'wheelEnabled', label: 'Mouse Wheel', type: 'bool', default: true },
  { name: 'touchEnabled', label: 'Touch', type: 'bool', default: true },
  { name: 'maxZoomFactor', label: 'Max Zoom', type: 'number', default: 256 },
  { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
  { name: 'controlBar.enabled', label: 'Control Bar', type: 'bool', default: true },
  { name: 'controlBar.position', label: 'Control Bar Pos', type: 'enum', options: ['top-left','top-right','bottom-left','bottom-right'], default: 'top-left' },
],

Sparkline: [
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'type', label: 'Type', type: 'enum', options: ['line','bar','spline','stepLine','area','splineArea','stepArea','winloss'], default: 'line' },
  { name: 'lineColor', label: 'Line Color', type: 'string', default: '#666666' },
  { name: 'lineWidth', label: 'Line Width', type: 'number', default: 2 },
  { name: 'showFirstLast', label: 'Show First/Last', type: 'bool', default: true },
  { name: 'showMinMax', label: 'Show Min/Max', type: 'bool', default: false },
  { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: true },
  { name: 'pointSymbol', label: 'Point Symbol', type: 'enum', options: ['circle','square','polygon','triangle','triangleDown'], default: 'circle' },
  { name: 'pointSize', label: 'Point Size', type: 'number', default: 4 },
],

Bullet: [
  { name: 'value', label: 'Value', type: 'number', default: 0 },
  { name: 'color', label: 'Bar Color', type: 'string', default: '#e8c267' },
  { name: 'targetColor', label: 'Target Color', type: 'string', default: '#666666' },
  { name: 'targetWidth', label: 'Target Width', type: 'number', default: 4 },
  { name: 'showTarget', label: 'Show Target', type: 'bool', default: true },
  { name: 'showZeroLevel', label: 'Show Zero Level', type: 'bool', default: true },
  { name: 'startScaleValue', label: 'Scale Start', type: 'number', default: 0 },
  { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: true },
],

BarGauge: [
  { name: 'values', label: 'Values', type: 'data', default: [] },
  { name: 'palette', label: 'Palette', type: 'enum', options: ['Material','Soft Pastel','Harmony Light','Office','Vintage','Violet'], default: 'Material' },
  { name: 'startValue', label: 'Start Value', type: 'number', default: 0 },
  { name: 'endValue', label: 'End Value', type: 'number', default: 100 },
  { name: 'barSpacing', label: 'Bar Spacing', type: 'number', default: 4 },
  { name: 'relativeInnerRadius', label: 'Inner Radius', type: 'number', default: 0.3 },
  { name: 'label.visible', label: 'Labels Visible', type: 'bool', default: true },
  { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
  { name: 'resolveLabelOverlapping', label: 'Label Overlap', type: 'enum', options: ['hide','none'], default: 'hide' },
],

LinearGauge: [
  { name: 'value', label: 'Value', type: 'number', default: 0 },
  { name: 'geometry.orientation', label: 'Orientation', type: 'enum', options: ['vertical','horizontal'], default: 'vertical' },
  { name: 'scale.startValue', label: 'Scale Start', type: 'number', default: 0 },
  { name: 'scale.endValue', label: 'Scale End', type: 'number', default: 100 },
  { name: 'rangeContainer.width', label: 'Range Width', type: 'number', default: 5 },
  { name: 'rangeContainer.offset', label: 'Range Offset', type: 'number', default: 0 },
  { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
],

CircularGauge: [
  { name: 'value', label: 'Value', type: 'number', default: 0 },
  { name: 'geometry.startAngle', label: 'Start Angle', type: 'number', default: 135 },
  { name: 'geometry.endAngle', label: 'End Angle', type: 'number', default: 405 },
  { name: 'scale.startValue', label: 'Scale Start', type: 'number', default: 0 },
  { name: 'scale.endValue', label: 'Scale End', type: 'number', default: 100 },
  { name: 'rangeContainer.width', label: 'Range Width', type: 'number', default: 5 },
  { name: 'rangeContainer.orientation', label: 'Range Orientation', type: 'enum', options: ['inside','outside','center'], default: 'outside' },
  { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
],

RangeSelector: [
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'value', label: 'Selected Range', type: 'data', default: [] },
  { name: 'selectedRangeColor', label: 'Selection Color', type: 'string', default: '#729ab4' },
  { name: 'selectedRangeUpdateMode', label: 'Update Mode', type: 'enum', options: ['reset','shift','keep'], default: 'reset' },
  { name: 'behavior.snapToTicks', label: 'Snap to Ticks', type: 'bool', default: true },
  { name: 'behavior.animationEnabled', label: 'Animation', type: 'bool', default: true },
  { name: 'behavior.allowSlidersSwap', label: 'Allow Swap', type: 'bool', default: true },
  { name: 'background.visible', label: 'Background Visible', type: 'bool', default: true },
],

PivotGrid: [
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'showBorders', label: 'Show Borders', type: 'bool', default: false },
  { name: 'showColumnGrandTotals', label: 'Col Grand Totals', type: 'bool', default: true },
  { name: 'showRowGrandTotals', label: 'Row Grand Totals', type: 'bool', default: true },
  { name: 'showColumnTotals', label: 'Col Totals', type: 'bool', default: true },
  { name: 'showRowTotals', label: 'Row Totals', type: 'bool', default: true },
  { name: 'allowSorting', label: 'Allow Sorting', type: 'bool', default: false },
  { name: 'allowFiltering', label: 'Allow Filtering', type: 'bool', default: false },
  { name: 'allowExpandAll', label: 'Allow Expand All', type: 'bool', default: false },
  { name: 'fieldPanel.visible', label: 'Field Panel', type: 'bool', default: false },
  { name: 'fieldChooser.enabled', label: 'Field Chooser', type: 'bool', default: true },
  { name: 'scrolling.mode', label: 'Scrolling Mode', type: 'enum', options: ['standard','virtual'], default: 'standard' },
  { name: 'wordWrapEnabled', label: 'Word Wrap', type: 'bool', default: false },
],

// ─── EDITORS ───────────────────────────────────────────────────────────────
TextBox: [
  { name: 'value', label: 'Value', type: 'string', default: '' },
  { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
  { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
  { name: 'mode', label: 'Mode', type: 'enum', options: ['text','password','email','search','tel','url'], default: 'text' },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
  { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
  { name: 'label', label: 'Label', type: 'string', default: '' },
  { name: 'labelMode', label: 'Label Mode', type: 'enum', options: ['static','floating','hidden','outside'], default: 'static' },
  { name: 'maxLength', label: 'Max Length', type: 'number', default: 0 },
  { name: 'spellcheck', label: 'Spellcheck', type: 'bool', default: false },
],

TextArea: [
  { name: 'value', label: 'Value', type: 'string', default: '' },
  { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
  { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
  { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
  { name: 'label', label: 'Label', type: 'string', default: '' },
  { name: 'autoResizeEnabled', label: 'Auto Resize', type: 'bool', default: false },
  { name: 'maxLength', label: 'Max Length', type: 'number', default: 0 },
  { name: 'spellcheck', label: 'Spellcheck', type: 'bool', default: false },
],

NumberBox: [
  { name: 'value', label: 'Value', type: 'number', default: 0 },
  { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
  { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
  { name: 'showSpinButtons', label: 'Spin Buttons', type: 'bool', default: false },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
  { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
  { name: 'label', label: 'Label', type: 'string', default: '' },
  { name: 'min', label: 'Min', type: 'number', default: 0 },
  { name: 'max', label: 'Max', type: 'number', default: 100 },
  { name: 'step', label: 'Step', type: 'number', default: 1 },
  { name: 'format', label: 'Format', type: 'string', default: '' },
],

CheckBox: [
  { name: 'text', label: 'Text', type: 'string', default: '' },
  { name: 'enableThreeStateBehavior', label: 'Three State', type: 'bool', default: false },
  { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
  { name: 'value', label: 'Default Value', type: 'bool', default: false },
],

SelectBox: [
  { name: 'value', label: 'Value', type: 'string', default: '' },
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'placeholder', label: 'Placeholder', type: 'string', default: 'Select...' },
  { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
  { name: 'searchEnabled', label: 'Search Enabled', type: 'bool', default: false },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
  { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
  { name: 'label', label: 'Label', type: 'string', default: '' },
  { name: 'labelMode', label: 'Label Mode', type: 'enum', options: ['static','floating','hidden','outside'], default: 'static' },
  { name: 'acceptCustomValue', label: 'Accept Custom', type: 'bool', default: false },
  { name: 'grouped', label: 'Grouped', type: 'bool', default: false },
  { name: 'openOnFieldClick', label: 'Open On Click', type: 'bool', default: false },
],

TagBox: [
  { name: 'value', label: 'Value', type: 'data', default: [] },
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
  { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
  { name: 'searchEnabled', label: 'Search Enabled', type: 'bool', default: true },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
  { name: 'showSelectionControls', label: 'Selection Controls', type: 'bool', default: false },
  { name: 'multiline', label: 'Multiline', type: 'bool', default: true },
  { name: 'selectAllMode', label: 'Select All Mode', type: 'enum', options: ['page','allPages'], default: 'page' },
  { name: 'applyValueMode', label: 'Apply Value Mode', type: 'enum', options: ['instantly','useButtons'], default: 'instantly' },
  { name: 'hideSelectedItems', label: 'Hide Selected', type: 'bool', default: false },
  { name: 'maxDisplayedTags', label: 'Max Tags Shown', type: 'number', default: 0 },
],

Lookup: [
  { name: 'value', label: 'Value', type: 'string', default: '' },
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'placeholder', label: 'Placeholder', type: 'string', default: 'Select...' },
  { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
  { name: 'searchEnabled', label: 'Search Enabled', type: 'bool', default: true },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
  { name: 'showCancelButton', label: 'Cancel Button', type: 'bool', default: true },
  { name: 'fullScreen', label: 'Full Screen', type: 'bool', default: false },
  { name: 'usePopover', label: 'Use Popover', type: 'bool', default: false },
  { name: 'applyValueMode', label: 'Apply Value Mode', type: 'enum', options: ['instantly','useButtons'], default: 'instantly' },
  { name: 'pageLoadMode', label: 'Page Load Mode', type: 'enum', options: ['scrollBottom','nextButton'], default: 'scrollBottom' },
  { name: 'pullRefreshEnabled', label: 'Pull to Refresh', type: 'bool', default: false },
],

Autocomplete: [
  { name: 'value', label: 'Value', type: 'string', default: '' },
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
  { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
  { name: 'minSearchLength', label: 'Min Search Length', type: 'number', default: 1 },
  { name: 'maxItemCount', label: 'Max Items', type: 'number', default: 10 },
  { name: 'searchMode', label: 'Search Mode', type: 'enum', options: ['startswith','contains'], default: 'startswith' },
  { name: 'searchTimeout', label: 'Search Timeout', type: 'number', default: 200 },
],

DropDownBox: [
  { name: 'value', label: 'Value', type: 'string', default: '' },
  { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
  { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
  { name: 'openOnFieldClick', label: 'Open On Click', type: 'bool', default: false },
  { name: 'acceptCustomValue', label: 'Accept Custom', type: 'bool', default: false },
  { name: 'deferRendering', label: 'Defer Rendering', type: 'bool', default: true },
],

DateBox: [
  { name: 'value', label: 'Value', type: 'string', default: '' },
  { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
  { name: 'type', label: 'Type', type: 'enum', options: ['date','time','datetime'], default: 'date' },
  { name: 'pickerType', label: 'Picker Type', type: 'enum', options: ['calendar','list','native','rollers'], default: 'calendar' },
  { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
  { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
  { name: 'label', label: 'Label', type: 'string', default: '' },
  { name: 'showTodayButton', label: 'Today Button', type: 'bool', default: false },
  { name: 'useMaskBehavior', label: 'Mask Behavior', type: 'bool', default: false },
  { name: 'displayFormat', label: 'Display Format', type: 'string', default: '' },
  { name: 'openOnFieldClick', label: 'Open On Click', type: 'bool', default: true },
  { name: 'applyValueMode', label: 'Apply Value Mode', type: 'enum', options: ['instantly','useButtons'], default: 'instantly' },
],

DateRangeBox: [
  { name: 'startDate', label: 'Start Date', type: 'string', default: '' },
  { name: 'endDate', label: 'End Date', type: 'string', default: '' },
  { name: 'startDateLabel', label: 'Start Label', type: 'string', default: 'Start Date' },
  { name: 'endDateLabel', label: 'End Label', type: 'string', default: 'End Date' },
  { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
  { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
  { name: 'multiView', label: 'Multi View', type: 'bool', default: true },
  { name: 'showTodayButton', label: 'Today Button', type: 'bool', default: false },
  { name: 'openOnFieldClick', label: 'Open On Click', type: 'bool', default: true },
  { name: 'applyValueMode', label: 'Apply Value Mode', type: 'enum', options: ['instantly','useButtons'], default: 'instantly' },
  { name: 'useMaskBehavior', label: 'Mask Behavior', type: 'bool', default: false },
],

ColorBox: [
  { name: 'value', label: 'Value', type: 'string', default: '' },
  { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
  { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
  { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
  { name: 'editAlphaChannel', label: 'Alpha Channel', type: 'bool', default: false },
  { name: 'applyValueMode', label: 'Apply Value Mode', type: 'enum', options: ['instantly','useButtons'], default: 'instantly' },
  { name: 'openOnFieldClick', label: 'Open On Click', type: 'bool', default: true },
],

Slider: [
  { name: 'value', label: 'Value', type: 'number', default: 0 },
  { name: 'min', label: 'Min', type: 'number', default: 0 },
  { name: 'max', label: 'Max', type: 'number', default: 100 },
  { name: 'step', label: 'Step', type: 'number', default: 1 },
  { name: 'showRange', label: 'Show Range', type: 'bool', default: true },
  { name: 'tooltip.enabled', label: 'Tooltip', type: 'bool', default: false },
  { name: 'tooltip.position', label: 'Tooltip Position', type: 'enum', options: ['top','bottom'], default: 'top' },
  { name: 'tooltip.showMode', label: 'Tooltip Show Mode', type: 'enum', options: ['onHover','always'], default: 'onHover' },
  { name: 'label.visible', label: 'Labels Visible', type: 'bool', default: false },
  { name: 'label.position', label: 'Label Position', type: 'enum', options: ['top','bottom'], default: 'bottom' },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
  { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
],

RangeSlider: [
  { name: 'value', label: 'Value (start, end)', type: 'data', default: [0,100] },
  { name: 'min', label: 'Min', type: 'number', default: 0 },
  { name: 'max', label: 'Max', type: 'number', default: 100 },
  { name: 'step', label: 'Step', type: 'number', default: 1 },
  { name: 'tooltip.enabled', label: 'Tooltip', type: 'bool', default: false },
  { name: 'tooltip.position', label: 'Tooltip Position', type: 'enum', options: ['top','bottom'], default: 'top' },
  { name: 'tooltip.showMode', label: 'Tooltip Show Mode', type: 'enum', options: ['onHover','always'], default: 'onHover' },
  { name: 'label.visible', label: 'Labels Visible', type: 'bool', default: false },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
  { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
],

Switch: [
  { name: 'switchedOnText', label: 'On Text', type: 'string', default: 'ON' },
  { name: 'switchedOffText', label: 'Off Text', type: 'string', default: 'OFF' },
  { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
  { name: 'value', label: 'Default Value', type: 'bool', default: false },
],

RadioGroup: [
  { name: 'value', label: 'Value', type: 'string', default: '' },
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'layout', label: 'Layout', type: 'enum', options: ['vertical','horizontal'], default: 'vertical' },
  { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
  { name: 'displayExpr', label: 'Display Expr', type: 'string', default: '', bindable: false },
  { name: 'valueExpr', label: 'Value Expr', type: 'string', default: '', bindable: false },
],

ButtonGroup: [
  { name: 'items', label: 'Items', type: 'data', default: [] },
  { name: 'selectionMode', label: 'Selection Mode', type: 'enum', options: ['none','single','multiple'], default: 'single' },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['contained','outlined','text'], default: 'contained' },
],

Calendar: [
  { name: 'value', label: 'Value', type: 'string', default: '' },
  { name: 'firstDayOfWeek', label: 'First Day of Week', type: 'enum', options: ['0','1','2','3','4','5','6'], default: '0' },
  { name: 'showTodayButton', label: 'Today Button', type: 'bool', default: false },
  { name: 'showOtherMonthDays', label: 'Other Month Days', type: 'bool', default: true },
  { name: 'showWeekNumbers', label: 'Week Numbers', type: 'bool', default: false },
  { name: 'zoomLevel', label: 'Zoom Level', type: 'enum', options: ['month','year','decade','century'], default: 'month' },
  { name: 'maxZoomLevel', label: 'Max Zoom Level', type: 'enum', options: ['month','year','decade','century'], default: 'month' },
  { name: 'minZoomLevel', label: 'Min Zoom Level', type: 'enum', options: ['month','year','decade','century'], default: 'century' },
  { name: 'selectionMode', label: 'Selection Mode', type: 'enum', options: ['single','multiple','range','week','month'], default: 'single' },
  { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
],

HtmlEditor: [
  { name: 'value', label: 'Value', type: 'string', default: '' },
  { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
  { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
  { name: 'valueType', label: 'Value Type', type: 'enum', options: ['html','markdown'], default: 'html' },
  { name: 'allowSoftLineBreak', label: 'Soft Line Break', type: 'bool', default: false },
  { name: 'mediaResizing.enabled', label: 'Media Resizing', type: 'bool', default: false },
  { name: 'tableResizing.enabled', label: 'Table Resizing', type: 'bool', default: false },
  { name: 'tableContextMenu.enabled', label: 'Table Context Menu', type: 'bool', default: false },
],

FileUploader: [
  { name: 'multiple', label: 'Multiple Files', type: 'bool', default: false },
  { name: 'uploadMode', label: 'Upload Mode', type: 'enum', options: ['instantly','useButtons','useForm'], default: 'instantly' },
  { name: 'uploadMethod', label: 'Upload Method', type: 'enum', options: ['POST','PUT'], default: 'POST' },
  { name: 'showFileList', label: 'Show File List', type: 'bool', default: true },
  { name: 'allowCanceling', label: 'Allow Canceling', type: 'bool', default: true },
  { name: 'selectButtonText', label: 'Select Button Text', type: 'string', default: 'Select File' },
  { name: 'labelText', label: 'Label Text', type: 'string', default: 'or Drop file here' },
  { name: 'accept', label: 'Accept', type: 'string', default: '' },
  { name: 'maxFileSize', label: 'Max File Size', type: 'number', default: 0 },
  { name: 'chunkSize', label: 'Chunk Size', type: 'number', default: 0 },
],

Form: [
  { name: 'formData', label: 'Form Data', type: 'data', default: {} },
  { name: 'colCount', label: 'Column Count', type: 'enum', options: ['1','2','3','4','auto'], default: '1' },
  { name: 'labelLocation', label: 'Label Location', type: 'enum', options: ['left','top','right'], default: 'left' },
  { name: 'labelMode', label: 'Label Mode', type: 'enum', options: ['outside','static','floating','hidden'], default: 'outside' },
  { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
  { name: 'showColonAfterLabel', label: 'Colon After Label', type: 'bool', default: true },
  { name: 'showRequiredMark', label: 'Required Mark', type: 'bool', default: true },
  { name: 'showOptionalMark', label: 'Optional Mark', type: 'bool', default: false },
  { name: 'showValidationSummary', label: 'Validation Summary', type: 'bool', default: false },
  { name: 'scrollingEnabled', label: 'Scrolling', type: 'bool', default: false },
  { name: 'alignItemLabels', label: 'Align Labels', type: 'bool', default: true },
],

// ─── DIALOGS & NOTIFICATIONS ───────────────────────────────────────────────
Popup: [
  { name: 'title', label: 'Title', type: 'string', default: 'Popup' },
  { name: 'showTitle', label: 'Show Title', type: 'bool', default: true },
  { name: 'showCloseButton', label: 'Close Button', type: 'bool', default: true },
  { name: 'dragEnabled', label: 'Drag Enabled', type: 'bool', default: true },
  { name: 'resizeEnabled', label: 'Resize Enabled', type: 'bool', default: false },
  { name: 'fullScreen', label: 'Full Screen', type: 'bool', default: false },
],

// ─── SCHEDULING ────────────────────────────────────────────────────────────
Scheduler: [
  { name: 'dataSource', label: 'Data Source', type: 'data', default: [] },
  { name: 'currentView', label: 'Current View', type: 'enum', options: ['day','week','workWeek','month','timelineDay','timelineWeek','timelineWorkWeek','timelineMonth','agenda'], default: 'week' },
  { name: 'firstDayOfWeek', label: 'First Day', type: 'enum', options: ['0','1','2','3','4','5','6'], default: '0' },
  { name: 'showAllDayPanel', label: 'All Day Panel', type: 'bool', default: true },
  { name: 'crossScrollingEnabled', label: 'Cross Scrolling', type: 'bool', default: false },
  { name: 'editing.allowAdding', label: 'Allow Adding', type: 'bool', default: true },
  { name: 'editing.allowDeleting', label: 'Allow Deleting', type: 'bool', default: true },
],

Gantt: [
  { name: 'tasks.dataSource', label: 'Tasks Data', type: 'data', default: [] },
  { name: 'taskListWidth', label: 'Task List Width', type: 'number', default: 300 },
  { name: 'showResources', label: 'Show Resources', type: 'bool', default: true },
  { name: 'scaleType', label: 'Scale Type', type: 'enum', options: ['auto','minutes','hours','days','weeks','months','quarters','years'], default: 'auto' },
  { name: 'editing.enabled', label: 'Editing Enabled', type: 'bool', default: false },
],

// ─── MISCELLANEOUS ─────────────────────────────────────────────────────────
Button: [
  { name: 'text', label: 'Text', type: 'string', default: 'Button' },
  { name: 'type', label: 'Type', type: 'enum', options: ['normal','default','back','danger','success'], default: 'normal' },
  { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['contained','outlined','text'], default: 'contained' },
  { name: 'icon', label: 'Icon', type: 'string', default: '' },
  { name: 'disabled', label: 'Disabled', type: 'bool', default: false },
],

};

export { WIDGET_PROPERTIES };
