// Widget catalog and property definitions

const DX_WIDGET_DATA = [
  { id: 'grids', parentId: null, name: 'Grids & Lists', assetType: 'category', assetLevel: 'category' },
  { id: 'charts', parentId: null, name: 'Charts & Visualization', assetType: 'category', assetLevel: 'category' },
  { id: 'editors', parentId: null, name: 'Editors', assetType: 'category', assetLevel: 'category' },
  { id: 'navigation', parentId: null, name: 'Navigation', assetType: 'category', assetLevel: 'category' },
  { id: 'layout', parentId: null, name: 'Layout', assetType: 'category', assetLevel: 'category' },
  { id: 'dialogs', parentId: null, name: 'Dialogs & Notifications', assetType: 'category', assetLevel: 'category' },
  { id: 'scheduling', parentId: null, name: 'Scheduling', assetType: 'category', assetLevel: 'category' },
  { id: 'misc', parentId: null, name: 'Miscellaneous', assetType: 'category', assetLevel: 'category' },

  // Grids & Lists
  { id: 'dx-datagrid', parentId: 'grids', name: 'DataGrid', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-treelist', parentId: 'grids', name: 'TreeList', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-cardview', parentId: 'grids', name: 'CardView', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-list', parentId: 'grids', name: 'List', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-treeview', parentId: 'grids', name: 'TreeView', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-gallery', parentId: 'grids', name: 'Gallery', assetType: 'widget', assetLevel: 'widget' },

  // Charts & Visualization
  { id: 'dx-chart', parentId: 'charts', name: 'Chart', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-piechart', parentId: 'charts', name: 'PieChart', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-polarchart', parentId: 'charts', name: 'PolarChart', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-funnel', parentId: 'charts', name: 'Funnel', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-sankey', parentId: 'charts', name: 'Sankey', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-treemap', parentId: 'charts', name: 'TreeMap', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-vectormap', parentId: 'charts', name: 'VectorMap', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-sparkline', parentId: 'charts', name: 'Sparkline', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-bullet', parentId: 'charts', name: 'Bullet', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-bargauge', parentId: 'charts', name: 'BarGauge', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-lineargauge', parentId: 'charts', name: 'LinearGauge', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-circulargauge', parentId: 'charts', name: 'CircularGauge', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-rangeselector', parentId: 'charts', name: 'RangeSelector', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-pivotgrid', parentId: 'charts', name: 'PivotGrid', assetType: 'widget', assetLevel: 'widget' },

  // Editors
  { id: 'dx-textbox', parentId: 'editors', name: 'TextBox', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-textarea', parentId: 'editors', name: 'TextArea', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-numberbox', parentId: 'editors', name: 'NumberBox', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-checkbox', parentId: 'editors', name: 'CheckBox', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-selectbox', parentId: 'editors', name: 'SelectBox', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-tagbox', parentId: 'editors', name: 'TagBox', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-lookup', parentId: 'editors', name: 'Lookup', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-autocomplete', parentId: 'editors', name: 'Autocomplete', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-dropdownbox', parentId: 'editors', name: 'DropDownBox', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-datebox', parentId: 'editors', name: 'DateBox', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-daterangebox', parentId: 'editors', name: 'DateRangeBox', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-colorbox', parentId: 'editors', name: 'ColorBox', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-slider', parentId: 'editors', name: 'Slider', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-rangeslider', parentId: 'editors', name: 'RangeSlider', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-switch', parentId: 'editors', name: 'Switch', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-radiogroup', parentId: 'editors', name: 'RadioGroup', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-buttongroup', parentId: 'editors', name: 'ButtonGroup', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-calendar', parentId: 'editors', name: 'Calendar', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-htmleditor', parentId: 'editors', name: 'HtmlEditor', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-fileuploader', parentId: 'editors', name: 'FileUploader', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-form', parentId: 'editors', name: 'Form', assetType: 'widget', assetLevel: 'widget' },

  // Navigation
  { id: 'dx-menu', parentId: 'navigation', name: 'Menu', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-contextmenu', parentId: 'navigation', name: 'ContextMenu', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-accordion', parentId: 'navigation', name: 'Accordion', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-tabs', parentId: 'navigation', name: 'Tabs', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-tabpanel', parentId: 'navigation', name: 'TabPanel', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-multiview', parentId: 'navigation', name: 'MultiView', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-toolbar', parentId: 'navigation', name: 'Toolbar', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-pagination', parentId: 'navigation', name: 'Pagination', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-stepper', parentId: 'navigation', name: 'Stepper', assetType: 'widget', assetLevel: 'widget' },

  // Layout
  { id: 'dx-box', parentId: 'layout', name: 'Box', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-responsivebox', parentId: 'layout', name: 'ResponsiveBox', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-splitter', parentId: 'layout', name: 'Splitter', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-scrollview', parentId: 'layout', name: 'ScrollView', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-resizable', parentId: 'layout', name: 'Resizable', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-draggable', parentId: 'layout', name: 'Draggable', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-sortable', parentId: 'layout', name: 'Sortable', assetType: 'widget', assetLevel: 'widget' },

  // Dialogs & Notifications
  { id: 'dx-popup', parentId: 'dialogs', name: 'Popup', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-popover', parentId: 'dialogs', name: 'Popover', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-tooltip', parentId: 'dialogs', name: 'Tooltip', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-toast', parentId: 'dialogs', name: 'Toast', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-loadpanel', parentId: 'dialogs', name: 'LoadPanel', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-loadindicator', parentId: 'dialogs', name: 'LoadIndicator', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-progressbar', parentId: 'dialogs', name: 'ProgressBar', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-actionsheet', parentId: 'dialogs', name: 'ActionSheet', assetType: 'widget', assetLevel: 'widget' },

  // Scheduling
  { id: 'dx-scheduler', parentId: 'scheduling', name: 'Scheduler', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-gantt', parentId: 'scheduling', name: 'Gantt', assetType: 'widget', assetLevel: 'widget' },

  // Miscellaneous
  { id: 'dx-button', parentId: 'misc', name: 'Button', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-dropdownbutton', parentId: 'misc', name: 'DropDownButton', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-speeddialalction', parentId: 'misc', name: 'SpeedDialAction', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-map', parentId: 'misc', name: 'Map', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-filemanager', parentId: 'misc', name: 'FileManager', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-diagram', parentId: 'misc', name: 'Diagram', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-chat', parentId: 'misc', name: 'Chat', assetType: 'widget', assetLevel: 'widget' },
  { id: 'dx-speechtotext', parentId: 'misc', name: 'SpeechToText', assetType: 'widget', assetLevel: 'widget' },
];

const STEPS = [
  { title: 'Select Asset' },
  { title: 'Step 2: Data Selection' },
  { title: 'Step 3: Placeholder' },
  { title: 'Step 4: Placeholder' },
];

const WIDGET_PROPERTIES = {
  // ─── GRIDS & LISTS ────────────────────────────────────────────────────────
  DataGrid: [
    { name: 'showBorders', label: 'Show Borders', type: 'bool', default: false },
    { name: 'showRowLines', label: 'Show Row Lines', type: 'bool', default: false },
    { name: 'showColumnLines', label: 'Show Column Lines', type: 'bool', default: true },
    { name: 'showColumnHeaders', label: 'Column Headers', type: 'bool', default: true },
    { name: 'allowColumnReordering', label: 'Col Reordering', type: 'bool', default: false },
    { name: 'allowColumnResizing', label: 'Col Resizing', type: 'bool', default: false },
    { name: 'columnAutoWidth', label: 'Column Auto Width', type: 'bool', default: false },
    { name: 'hoverStateEnabled', label: 'Hover State', type: 'bool', default: false },
    { name: 'rowAlternationEnabled', label: 'Row Alternation', type: 'bool', default: false },
    { name: 'wordWrapEnabled', label: 'Word Wrap', type: 'bool', default: false },
    { name: 'pager.visible', label: 'Pager Visible', type: 'bool', default: true },
    { name: 'searchPanel.visible', label: 'Search Panel', type: 'bool', default: false },
    { name: 'filterRow.visible', label: 'Filter Row', type: 'bool', default: false },
    { name: 'groupPanel.visible', label: 'Group Panel', type: 'bool', default: false },
    { name: 'headerFilter.visible', label: 'Header Filter', type: 'bool', default: false },
    { name: 'selection.mode', label: 'Selection Mode', type: 'enum', options: ['none','single','multiple'], default: 'none' },
    { name: 'editing.mode', label: 'Edit Mode', type: 'enum', options: ['row','cell','batch','form','popup'], default: 'row' },
    { name: 'editing.allowAdding', label: 'Allow Adding', type: 'bool', default: false },
    { name: 'editing.allowUpdating', label: 'Allow Updating', type: 'bool', default: false },
    { name: 'editing.allowDeleting', label: 'Allow Deleting', type: 'bool', default: false },
    { name: 'scrolling.mode', label: 'Scrolling Mode', type: 'enum', options: ['standard','virtual','infinite'], default: 'standard' },
    { name: 'paging.pageSize', label: 'Page Size', type: 'number', default: 20 },
  ],
  TreeList: [
    { name: 'showBorders', label: 'Show Borders', type: 'bool', default: false },
    { name: 'showRowLines', label: 'Show Row Lines', type: 'bool', default: false },
    { name: 'showColumnLines', label: 'Show Column Lines', type: 'bool', default: true },
    { name: 'allowColumnResizing', label: 'Col Resizing', type: 'bool', default: false },
    { name: 'autoExpandAll', label: 'Auto Expand All', type: 'bool', default: false },
    { name: 'hoverStateEnabled', label: 'Hover State', type: 'bool', default: false },
    { name: 'rowAlternationEnabled', label: 'Row Alternation', type: 'bool', default: false },
    { name: 'filterRow.visible', label: 'Filter Row', type: 'bool', default: false },
    { name: 'searchPanel.visible', label: 'Search Panel', type: 'bool', default: false },
    { name: 'selection.mode', label: 'Selection Mode', type: 'enum', options: ['none','single','multiple'], default: 'none' },
    { name: 'selection.recursive', label: 'Recursive Select', type: 'bool', default: false },
    { name: 'editing.mode', label: 'Edit Mode', type: 'enum', options: ['row','cell','batch','form','popup'], default: 'row' },
    { name: 'editing.allowAdding', label: 'Allow Adding', type: 'bool', default: false },
    { name: 'editing.allowUpdating', label: 'Allow Updating', type: 'bool', default: false },
    { name: 'editing.allowDeleting', label: 'Allow Deleting', type: 'bool', default: false },
    { name: 'scrolling.mode', label: 'Scrolling Mode', type: 'enum', options: ['standard','virtual'], default: 'standard' },
    { name: 'keyExpr', label: 'Key Expr', type: 'string', default: 'id' },
    { name: 'parentIdExpr', label: 'Parent ID Expr', type: 'string', default: 'parentId' },
  ],
  List: [
    { name: 'selectionMode', label: 'Selection Mode', type: 'enum', options: ['none','single','multiple','all'], default: 'none' },
    { name: 'showSelectionControls', label: 'Selection Controls', type: 'bool', default: false },
    { name: 'searchEnabled', label: 'Search Enabled', type: 'bool', default: false },
    { name: 'allowItemDeleting', label: 'Allow Delete', type: 'bool', default: false },
    { name: 'allowItemReordering', label: 'Allow Reorder', type: 'bool', default: false },
    { name: 'grouped', label: 'Grouped', type: 'bool', default: false },
    { name: 'pullRefreshEnabled', label: 'Pull to Refresh', type: 'bool', default: false },
    { name: 'pageLoadMode', label: 'Page Load Mode', type: 'enum', options: ['scrollBottom','nextButton'], default: 'scrollBottom' },
    { name: 'showScrollbar', label: 'Show Scrollbar', type: 'enum', options: ['onScroll','onHover','always','never'], default: 'onScroll' },
    { name: 'noDataText', label: 'No Data Text', type: 'string', default: 'No data' },
  ],
  TreeView: [
    { name: 'showCheckBoxesMode', label: 'Checkboxes', type: 'enum', options: ['none','normal','selectAll'], default: 'none' },
    { name: 'selectionMode', label: 'Selection Mode', type: 'enum', options: ['single','multiple'], default: 'multiple' },
    { name: 'searchEnabled', label: 'Search Enabled', type: 'bool', default: false },
    { name: 'expandAllEnabled', label: 'Expand All Button', type: 'bool', default: false },
    { name: 'selectByClick', label: 'Select by Click', type: 'bool', default: false },
    { name: 'selectNodesRecursive', label: 'Recursive Select', type: 'bool', default: true },
    { name: 'expandNodesRecursive', label: 'Recursive Expand', type: 'bool', default: true },
    { name: 'animationEnabled', label: 'Animation', type: 'bool', default: true },
    { name: 'dataStructure', label: 'Data Structure', type: 'enum', options: ['tree','plain'], default: 'tree' },
    { name: 'noDataText', label: 'No Data Text', type: 'string', default: 'No data' },
  ],
  Gallery: [
    { name: 'loop', label: 'Loop', type: 'bool', default: false },
    { name: 'showIndicator', label: 'Show Indicator', type: 'bool', default: true },
    { name: 'showNavButtons', label: 'Nav Buttons', type: 'bool', default: false },
    { name: 'swipeEnabled', label: 'Swipe Enabled', type: 'bool', default: true },
    { name: 'stretchImages', label: 'Stretch Images', type: 'bool', default: false },
    { name: 'animationEnabled', label: 'Animation', type: 'bool', default: true },
    { name: 'animationDuration', label: 'Animation Duration', type: 'number', default: 400 },
    { name: 'slideshowDelay', label: 'Slideshow Delay', type: 'number', default: 0 },
    { name: 'wrapAround', label: 'Wrap Around', type: 'bool', default: false },
  ],

  // ─── EDITORS ──────────────────────────────────────────────────────────────
  TextBox: [
    { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
    { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
    { name: 'mode', label: 'Mode', type: 'enum', options: ['text','password','email','search','tel','url'], default: 'text' },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
    { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
    { name: 'label', label: 'Label', type: 'string', default: '' },
    { name: 'labelMode', label: 'Label Mode', type: 'enum', options: ['static','floating','hidden','outside'], default: 'static' },
    { name: 'maxLength', label: 'Max Length', type: 'number', default: 0 },
    { name: 'spellcheck', label: 'Spellcheck', type: 'bool', default: false },
  ],
  TextArea: [
    { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
    { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
    { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
    { name: 'label', label: 'Label', type: 'string', default: '' },
    { name: 'autoResizeEnabled', label: 'Auto Resize', type: 'bool', default: false },
    { name: 'maxLength', label: 'Max Length', type: 'number', default: 0 },
    { name: 'spellcheck', label: 'Spellcheck', type: 'bool', default: false },
  ],
  NumberBox: [
    { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
    { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
    { name: 'showSpinButtons', label: 'Spin Buttons', type: 'bool', default: false },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
    { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
    { name: 'label', label: 'Label', type: 'string', default: '' },
    { name: 'min', label: 'Min', type: 'number', default: 0 },
    { name: 'max', label: 'Max', type: 'number', default: 100 },
    { name: 'step', label: 'Step', type: 'number', default: 1 },
    { name: 'format', label: 'Format', type: 'string', default: '' },
  ],
  CheckBox: [
    { name: 'text', label: 'Text', type: 'string', default: '' },
    { name: 'enableThreeStateBehavior', label: 'Three State', type: 'bool', default: false },
    { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
    { name: 'value', label: 'Default Value', type: 'bool', default: false },
  ],
  SelectBox: [
    { name: 'placeholder', label: 'Placeholder', type: 'string', default: 'Select...' },
    { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
    { name: 'searchEnabled', label: 'Search Enabled', type: 'bool', default: false },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
    { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
    { name: 'label', label: 'Label', type: 'string', default: '' },
    { name: 'labelMode', label: 'Label Mode', type: 'enum', options: ['static','floating','hidden','outside'], default: 'static' },
    { name: 'acceptCustomValue', label: 'Accept Custom', type: 'bool', default: false },
    { name: 'grouped', label: 'Grouped', type: 'bool', default: false },
    { name: 'openOnFieldClick', label: 'Open On Click', type: 'bool', default: false },
  ],
  TagBox: [
    { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
    { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
    { name: 'searchEnabled', label: 'Search Enabled', type: 'bool', default: true },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
    { name: 'showSelectionControls', label: 'Selection Controls', type: 'bool', default: false },
    { name: 'multiline', label: 'Multiline', type: 'bool', default: true },
    { name: 'selectAllMode', label: 'Select All Mode', type: 'enum', options: ['page','allPages'], default: 'page' },
    { name: 'applyValueMode', label: 'Apply Value Mode', type: 'enum', options: ['instantly','useButtons'], default: 'instantly' },
    { name: 'hideSelectedItems', label: 'Hide Selected', type: 'bool', default: false },
    { name: 'maxDisplayedTags', label: 'Max Tags Shown', type: 'number', default: 0 },
  ],
  Lookup: [
    { name: 'placeholder', label: 'Placeholder', type: 'string', default: 'Select...' },
    { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
    { name: 'searchEnabled', label: 'Search Enabled', type: 'bool', default: true },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
    { name: 'showCancelButton', label: 'Cancel Button', type: 'bool', default: true },
    { name: 'fullScreen', label: 'Full Screen', type: 'bool', default: false },
    { name: 'usePopover', label: 'Use Popover', type: 'bool', default: false },
    { name: 'applyValueMode', label: 'Apply Value Mode', type: 'enum', options: ['instantly','useButtons'], default: 'instantly' },
    { name: 'pageLoadMode', label: 'Page Load Mode', type: 'enum', options: ['scrollBottom','nextButton'], default: 'scrollBottom' },
    { name: 'pullRefreshEnabled', label: 'Pull to Refresh', type: 'bool', default: false },
  ],
  Autocomplete: [
    { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
    { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
    { name: 'minSearchLength', label: 'Min Search Length', type: 'number', default: 1 },
    { name: 'maxItemCount', label: 'Max Items', type: 'number', default: 10 },
    { name: 'searchMode', label: 'Search Mode', type: 'enum', options: ['startswith','contains'], default: 'startswith' },
    { name: 'searchTimeout', label: 'Search Timeout', type: 'number', default: 200 },
  ],
  DropDownBox: [
    { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
    { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
    { name: 'openOnFieldClick', label: 'Open On Click', type: 'bool', default: false },
    { name: 'acceptCustomValue', label: 'Accept Custom', type: 'bool', default: false },
    { name: 'deferRendering', label: 'Defer Rendering', type: 'bool', default: true },
  ],
  DateBox: [
    { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
    { name: 'type', label: 'Type', type: 'enum', options: ['date','time','datetime'], default: 'date' },
    { name: 'pickerType', label: 'Picker Type', type: 'enum', options: ['calendar','list','native','rollers'], default: 'calendar' },
    { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
    { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
    { name: 'label', label: 'Label', type: 'string', default: '' },
    { name: 'showTodayButton', label: 'Today Button', type: 'bool', default: false },
    { name: 'useMaskBehavior', label: 'Mask Behavior', type: 'bool', default: false },
    { name: 'displayFormat', label: 'Display Format', type: 'string', default: '' },
    { name: 'openOnFieldClick', label: 'Open On Click', type: 'bool', default: true },
    { name: 'applyValueMode', label: 'Apply Value Mode', type: 'enum', options: ['instantly','useButtons'], default: 'instantly' },
  ],
  DateRangeBox: [
    { name: 'startDateLabel', label: 'Start Label', type: 'string', default: 'Start Date' },
    { name: 'endDateLabel', label: 'End Label', type: 'string', default: 'End Date' },
    { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
    { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
    { name: 'multiView', label: 'Multi View', type: 'bool', default: true },
    { name: 'showTodayButton', label: 'Today Button', type: 'bool', default: false },
    { name: 'openOnFieldClick', label: 'Open On Click', type: 'bool', default: true },
    { name: 'applyValueMode', label: 'Apply Value Mode', type: 'enum', options: ['instantly','useButtons'], default: 'instantly' },
    { name: 'useMaskBehavior', label: 'Mask Behavior', type: 'bool', default: false },
  ],
  ColorBox: [
    { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
    { name: 'showClearButton', label: 'Clear Button', type: 'bool', default: false },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
    { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
    { name: 'editAlphaChannel', label: 'Alpha Channel', type: 'bool', default: false },
    { name: 'applyValueMode', label: 'Apply Value Mode', type: 'enum', options: ['instantly','useButtons'], default: 'instantly' },
    { name: 'openOnFieldClick', label: 'Open On Click', type: 'bool', default: true },
  ],
  Slider: [
    { name: 'min', label: 'Min', type: 'number', default: 0 },
    { name: 'max', label: 'Max', type: 'number', default: 100 },
    { name: 'step', label: 'Step', type: 'number', default: 1 },
    { name: 'showRange', label: 'Show Range', type: 'bool', default: true },
    { name: 'tooltip.enabled', label: 'Tooltip', type: 'bool', default: false },
    { name: 'tooltip.position', label: 'Tooltip Position', type: 'enum', options: ['top','bottom'], default: 'top' },
    { name: 'tooltip.showMode', label: 'Tooltip Show Mode', type: 'enum', options: ['onHover','always'], default: 'onHover' },
    { name: 'label.visible', label: 'Labels Visible', type: 'bool', default: false },
    { name: 'label.position', label: 'Label Position', type: 'enum', options: ['top','bottom'], default: 'bottom' },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
    { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
  ],
  RangeSlider: [
    { name: 'min', label: 'Min', type: 'number', default: 0 },
    { name: 'max', label: 'Max', type: 'number', default: 100 },
    { name: 'step', label: 'Step', type: 'number', default: 1 },
    { name: 'tooltip.enabled', label: 'Tooltip', type: 'bool', default: false },
    { name: 'tooltip.position', label: 'Tooltip Position', type: 'enum', options: ['top','bottom'], default: 'top' },
    { name: 'tooltip.showMode', label: 'Tooltip Show Mode', type: 'enum', options: ['onHover','always'], default: 'onHover' },
    { name: 'label.visible', label: 'Labels Visible', type: 'bool', default: false },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
    { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
  ],
  Switch: [
    { name: 'switchedOnText', label: 'On Text', type: 'string', default: 'ON' },
    { name: 'switchedOffText', label: 'Off Text', type: 'string', default: 'OFF' },
    { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
    { name: 'value', label: 'Default Value', type: 'bool', default: false },
  ],
  RadioGroup: [
    { name: 'layout', label: 'Layout', type: 'enum', options: ['vertical','horizontal'], default: 'vertical' },
    { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
    { name: 'displayExpr', label: 'Display Expr', type: 'string', default: '' },
    { name: 'valueExpr', label: 'Value Expr', type: 'string', default: '' },
  ],
  ButtonGroup: [
    { name: 'selectionMode', label: 'Selection Mode', type: 'enum', options: ['none','single','multiple'], default: 'single' },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['contained','outlined','text'], default: 'contained' },
  ],
  Calendar: [
    { name: 'firstDayOfWeek', label: 'First Day of Week', type: 'enum', options: ['0','1','2','3','4','5','6'], default: '0' },
    { name: 'showTodayButton', label: 'Today Button', type: 'bool', default: false },
    { name: 'showOtherMonthDays', label: 'Other Month Days', type: 'bool', default: true },
    { name: 'showWeekNumbers', label: 'Week Numbers', type: 'bool', default: false },
    { name: 'zoomLevel', label: 'Zoom Level', type: 'enum', options: ['month','year','decade','century'], default: 'month' },
    { name: 'maxZoomLevel', label: 'Max Zoom Level', type: 'enum', options: ['month','year','decade','century'], default: 'month' },
    { name: 'minZoomLevel', label: 'Min Zoom Level', type: 'enum', options: ['month','year','decade','century'], default: 'century' },
    { name: 'selectionMode', label: 'Selection Mode', type: 'enum', options: ['single','multiple','range','week','month'], default: 'single' },
    { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
  ],
  HtmlEditor: [
    { name: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
    { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['outlined','filled','underlined'], default: 'outlined' },
    { name: 'valueType', label: 'Value Type', type: 'enum', options: ['html','markdown'], default: 'html' },
    { name: 'allowSoftLineBreak', label: 'Soft Line Break', type: 'bool', default: false },
    { name: 'mediaResizing.enabled', label: 'Media Resizing', type: 'bool', default: false },
    { name: 'tableResizing.enabled', label: 'Table Resizing', type: 'bool', default: false },
    { name: 'tableContextMenu.enabled', label: 'Table Context Menu', type: 'bool', default: false },
  ],
  FileUploader: [
    { name: 'multiple', label: 'Multiple Files', type: 'bool', default: false },
    { name: 'uploadMode', label: 'Upload Mode', type: 'enum', options: ['instantly','useButtons','useForm'], default: 'instantly' },
    { name: 'uploadMethod', label: 'Upload Method', type: 'enum', options: ['POST','PUT'], default: 'POST' },
    { name: 'showFileList', label: 'Show File List', type: 'bool', default: true },
    { name: 'allowCanceling', label: 'Allow Canceling', type: 'bool', default: true },
    { name: 'selectButtonText', label: 'Select Button Text', type: 'string', default: 'Select File' },
    { name: 'labelText', label: 'Label Text', type: 'string', default: 'or Drop file here' },
    { name: 'accept', label: 'Accept', type: 'string', default: '' },
    { name: 'maxFileSize', label: 'Max File Size', type: 'number', default: 0 },
    { name: 'chunkSize', label: 'Chunk Size', type: 'number', default: 0 },
  ],
  Form: [
    { name: 'colCount', label: 'Column Count', type: 'enum', options: ['1','2','3','4','auto'], default: '1' },
    { name: 'labelLocation', label: 'Label Location', type: 'enum', options: ['left','top','right'], default: 'left' },
    { name: 'labelMode', label: 'Label Mode', type: 'enum', options: ['outside','static','floating','hidden'], default: 'outside' },
    { name: 'readOnly', label: 'Read Only', type: 'bool', default: false },
    { name: 'showColonAfterLabel', label: 'Colon After Label', type: 'bool', default: true },
    { name: 'showRequiredMark', label: 'Required Mark', type: 'bool', default: true },
    { name: 'showOptionalMark', label: 'Optional Mark', type: 'bool', default: false },
    { name: 'showValidationSummary', label: 'Validation Summary', type: 'bool', default: false },
    { name: 'scrollingEnabled', label: 'Scrolling', type: 'bool', default: false },
    { name: 'alignItemLabels', label: 'Align Labels', type: 'bool', default: true },
  ],

  // ─── CHARTS & VISUALIZATION (existing) ───────────────────────────────────
  Chart: [
    { name: 'palette', label: 'Palette', type: 'enum', options: ['Material','Soft Pastel','Harmony Light','Office','Vintage','Violet','Carmine','Dark Moon','Soft Blue','Dark Violet','Green Mist'], default: 'Material' },
    { name: 'legend.visible', label: 'Legend Visible', type: 'bool', default: true },
    { name: 'legend.position', label: 'Legend Position', type: 'enum', options: ['inside','outside'], default: 'outside' },
    { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
    { name: 'commonSeriesSettings.type', label: 'Series Type', type: 'enum', options: ['line','bar','area','spline','scatter','stepLine','fullStackedBar','stackedBar'], default: 'line' },
    { name: 'scrollBar.visible', label: 'Scroll Bar', type: 'bool', default: false },
    { name: 'zoomAndPan.argumentAxis', label: 'Zoom Argument Axis', type: 'enum', options: ['none','zoom','pan','both'], default: 'none' },
  ],
  PieChart: [
    { name: 'palette', label: 'Palette', type: 'enum', options: ['Material','Soft Pastel','Harmony Light','Office','Vintage','Violet'], default: 'Material' },
    { name: 'legend.visible', label: 'Legend Visible', type: 'bool', default: true },
    { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
    { name: 'type', label: 'Type', type: 'enum', options: ['pie','donut'], default: 'pie' },
    { name: 'innerRadius', label: 'Inner Radius', type: 'number', default: 0.5 },
  ],
  Scheduler: [
    { name: 'currentView', label: 'Current View', type: 'enum', options: ['day','week','workWeek','month','timelineDay','timelineWeek','timelineWorkWeek','timelineMonth','agenda'], default: 'week' },
    { name: 'firstDayOfWeek', label: 'First Day', type: 'enum', options: ['0','1','2','3','4','5','6'], default: '0' },
    { name: 'showAllDayPanel', label: 'All Day Panel', type: 'bool', default: true },
    { name: 'crossScrollingEnabled', label: 'Cross Scrolling', type: 'bool', default: false },
    { name: 'editing.allowAdding', label: 'Allow Adding', type: 'bool', default: true },
    { name: 'editing.allowDeleting', label: 'Allow Deleting', type: 'bool', default: true },
  ],
  Gantt: [
    { name: 'taskListWidth', label: 'Task List Width', type: 'number', default: 300 },
    { name: 'showResources', label: 'Show Resources', type: 'bool', default: true },
    { name: 'scaleType', label: 'Scale Type', type: 'enum', options: ['auto','minutes','hours','days','weeks','months','quarters','years'], default: 'auto' },
    { name: 'editing.enabled', label: 'Editing Enabled', type: 'bool', default: false },
  ],
  Popup: [
    { name: 'title', label: 'Title', type: 'string', default: 'Popup' },
    { name: 'showTitle', label: 'Show Title', type: 'bool', default: true },
    { name: 'showCloseButton', label: 'Close Button', type: 'bool', default: true },
    { name: 'dragEnabled', label: 'Drag Enabled', type: 'bool', default: true },
    { name: 'resizeEnabled', label: 'Resize Enabled', type: 'bool', default: false },
    { name: 'fullScreen', label: 'Full Screen', type: 'bool', default: false },
  ],
  Button: [
    { name: 'text', label: 'Text', type: 'string', default: 'Button' },
    { name: 'type', label: 'Type', type: 'enum', options: ['normal','default','back','danger','success'], default: 'normal' },
    { name: 'stylingMode', label: 'Styling Mode', type: 'enum', options: ['contained','outlined','text'], default: 'contained' },
    { name: 'icon', label: 'Icon', type: 'string', default: '' },
    { name: 'disabled', label: 'Disabled', type: 'bool', default: false },
  ],
  PolarChart: [
    { name: 'palette', label: 'Palette', type: 'enum', options: ['Material','Soft Pastel','Harmony Light','Office','Vintage','Violet'], default: 'Material' },
    { name: 'useSpiderWeb', label: 'Spider Web', type: 'bool', default: false },
    { name: 'commonSeriesSettings.type', label: 'Series Type', type: 'enum', options: ['line','area','bar','scatter','stackedLine','stackedArea','fullStackedLine','fullStackedArea'], default: 'scatter' },
    { name: 'legend.visible', label: 'Legend Visible', type: 'bool', default: true },
    { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
    { name: 'commonSeriesSettings.closed', label: 'Closed Series', type: 'bool', default: true },
  ],
  Funnel: [
    { name: 'algorithm', label: 'Algorithm', type: 'enum', options: ['dynamicSlope','dynamicHeight'], default: 'dynamicSlope' },
    { name: 'palette', label: 'Palette', type: 'enum', options: ['Material','Soft Pastel','Harmony Light','Office','Vintage','Violet'], default: 'Material' },
    { name: 'inverted', label: 'Inverted', type: 'bool', default: false },
    { name: 'sortData', label: 'Sort Data', type: 'bool', default: true },
    { name: 'label.visible', label: 'Labels Visible', type: 'bool', default: true },
    { name: 'label.position', label: 'Label Position', type: 'enum', options: ['inside','outside','columns'], default: 'columns' },
    { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
    { name: 'resolveLabelOverlapping', label: 'Overlap Mode', type: 'enum', options: ['shift','hide','none'], default: 'shift' },
  ],
  Sankey: [
    { name: 'palette', label: 'Palette', type: 'enum', options: ['Material','Soft Pastel','Harmony Light','Office','Vintage','Violet'], default: 'Material' },
    { name: 'alignment', label: 'Alignment', type: 'enum', options: ['top','center','bottom'], default: 'center' },
    { name: 'label.visible', label: 'Labels Visible', type: 'bool', default: true },
    { name: 'link.colorMode', label: 'Link Color Mode', type: 'enum', options: ['none','source','target','gradient'], default: 'none' },
    { name: 'link.opacity', label: 'Link Opacity', type: 'number', default: 0.3 },
    { name: 'node.width', label: 'Node Width', type: 'number', default: 30 },
    { name: 'node.padding', label: 'Node Padding', type: 'number', default: 30 },
    { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
  ],
  TreeMap: [
    { name: 'palette', label: 'Palette', type: 'enum', options: ['Material','Soft Pastel','Harmony Light','Office','Vintage','Violet'], default: 'Material' },
    { name: 'layoutAlgorithm', label: 'Layout Algorithm', type: 'enum', options: ['squarified','strip','sliceanddice'], default: 'squarified' },
    { name: 'layoutDirection', label: 'Layout Direction', type: 'enum', options: ['leftTopRightBottom','leftBottomRightTop','rightTopLeftBottom','rightBottomLeftTop'], default: 'leftTopRightBottom' },
    { name: 'colorizer.type', label: 'Colorizer Type', type: 'enum', options: ['none','gradient','range','discrete'], default: 'none' },
    { name: 'colorizer.colorizeGroups', label: 'Colorize Groups', type: 'bool', default: false },
    { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
    { name: 'maxDepth', label: 'Max Depth', type: 'number', default: 2 },
    { name: 'resolveLabelOverlapping', label: 'Label Overlap', type: 'enum', options: ['hide','none'], default: 'hide' },
  ],
  VectorMap: [
    { name: 'projection', label: 'Projection', type: 'enum', options: ['mercator','equirectangular','lambert','miller'], default: 'mercator' },
    { name: 'panningEnabled', label: 'Panning', type: 'bool', default: true },
    { name: 'zoomingEnabled', label: 'Zooming', type: 'bool', default: true },
    { name: 'wheelEnabled', label: 'Mouse Wheel', type: 'bool', default: true },
    { name: 'touchEnabled', label: 'Touch', type: 'bool', default: true },
    { name: 'maxZoomFactor', label: 'Max Zoom', type: 'number', default: 256 },
    { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
    { name: 'controlBar.enabled', label: 'Control Bar', type: 'bool', default: true },
    { name: 'controlBar.position', label: 'Control Bar Pos', type: 'enum', options: ['top-left','top-right','bottom-left','bottom-right'], default: 'top-left' },
  ],
  Sparkline: [
    { name: 'type', label: 'Type', type: 'enum', options: ['line','bar','spline','stepLine','area','splineArea','stepArea','winloss'], default: 'line' },
    { name: 'lineColor', label: 'Line Color', type: 'string', default: '#666666' },
    { name: 'lineWidth', label: 'Line Width', type: 'number', default: 2 },
    { name: 'showFirstLast', label: 'Show First/Last', type: 'bool', default: true },
    { name: 'showMinMax', label: 'Show Min/Max', type: 'bool', default: false },
    { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: true },
    { name: 'pointSymbol', label: 'Point Symbol', type: 'enum', options: ['circle','square','polygon','triangle','triangleDown'], default: 'circle' },
    { name: 'pointSize', label: 'Point Size', type: 'number', default: 4 },
  ],
  Bullet: [
    { name: 'color', label: 'Bar Color', type: 'string', default: '#e8c267' },
    { name: 'targetColor', label: 'Target Color', type: 'string', default: '#666666' },
    { name: 'targetWidth', label: 'Target Width', type: 'number', default: 4 },
    { name: 'showTarget', label: 'Show Target', type: 'bool', default: true },
    { name: 'showZeroLevel', label: 'Show Zero Level', type: 'bool', default: true },
    { name: 'startScaleValue', label: 'Scale Start', type: 'number', default: 0 },
    { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: true },
  ],
  BarGauge: [
    { name: 'palette', label: 'Palette', type: 'enum', options: ['Material','Soft Pastel','Harmony Light','Office','Vintage','Violet'], default: 'Material' },
    { name: 'startValue', label: 'Start Value', type: 'number', default: 0 },
    { name: 'endValue', label: 'End Value', type: 'number', default: 100 },
    { name: 'barSpacing', label: 'Bar Spacing', type: 'number', default: 4 },
    { name: 'relativeInnerRadius', label: 'Inner Radius', type: 'number', default: 0.3 },
    { name: 'label.visible', label: 'Labels Visible', type: 'bool', default: true },
    { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
    { name: 'resolveLabelOverlapping', label: 'Label Overlap', type: 'enum', options: ['hide','none'], default: 'hide' },
  ],
  LinearGauge: [
    { name: 'geometry.orientation', label: 'Orientation', type: 'enum', options: ['vertical','horizontal'], default: 'vertical' },
    { name: 'scale.startValue', label: 'Scale Start', type: 'number', default: 0 },
    { name: 'scale.endValue', label: 'Scale End', type: 'number', default: 100 },
    { name: 'rangeContainer.width', label: 'Range Width', type: 'number', default: 5 },
    { name: 'rangeContainer.offset', label: 'Range Offset', type: 'number', default: 0 },
    { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
  ],
  CircularGauge: [
    { name: 'geometry.startAngle', label: 'Start Angle', type: 'number', default: 135 },
    { name: 'geometry.endAngle', label: 'End Angle', type: 'number', default: 405 },
    { name: 'scale.startValue', label: 'Scale Start', type: 'number', default: 0 },
    { name: 'scale.endValue', label: 'Scale End', type: 'number', default: 100 },
    { name: 'rangeContainer.width', label: 'Range Width', type: 'number', default: 5 },
    { name: 'rangeContainer.orientation', label: 'Range Orientation', type: 'enum', options: ['inside','outside','center'], default: 'outside' },
    { name: 'tooltip.enabled', label: 'Tooltip Enabled', type: 'bool', default: false },
  ],
  RangeSelector: [
    { name: 'selectedRangeColor', label: 'Selection Color', type: 'string', default: '#729ab4' },
    { name: 'selectedRangeUpdateMode', label: 'Update Mode', type: 'enum', options: ['reset','shift','keep'], default: 'reset' },
    { name: 'behavior.snapToTicks', label: 'Snap to Ticks', type: 'bool', default: true },
    { name: 'behavior.animationEnabled', label: 'Animation', type: 'bool', default: true },
    { name: 'behavior.allowSlidersSwap', label: 'Allow Swap', type: 'bool', default: true },
    { name: 'background.visible', label: 'Background Visible', type: 'bool', default: true },
  ],
  PivotGrid: [
    { name: 'showBorders', label: 'Show Borders', type: 'bool', default: false },
    { name: 'showColumnGrandTotals', label: 'Col Grand Totals', type: 'bool', default: true },
    { name: 'showRowGrandTotals', label: 'Row Grand Totals', type: 'bool', default: true },
    { name: 'showColumnTotals', label: 'Col Totals', type: 'bool', default: true },
    { name: 'showRowTotals', label: 'Row Totals', type: 'bool', default: true },
    { name: 'allowSorting', label: 'Allow Sorting', type: 'bool', default: false },
    { name: 'allowFiltering', label: 'Allow Filtering', type: 'bool', default: false },
    { name: 'allowExpandAll', label: 'Allow Expand All', type: 'bool', default: false },
    { name: 'fieldPanel.visible', label: 'Field Panel', type: 'bool', default: false },
    { name: 'fieldChooser.enabled', label: 'Field Chooser', type: 'bool', default: true },
    { name: 'scrolling.mode', label: 'Scrolling Mode', type: 'enum', options: ['standard','virtual'], default: 'standard' },
    { name: 'wordWrapEnabled', label: 'Word Wrap', type: 'bool', default: false },
  ],
};

export { DX_WIDGET_DATA, WIDGET_PROPERTIES };
